### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by angieCat** [cnblogs/coder-service#1]
https://www.cnblogs.com/xrq730/p/4854820.html
这篇博文误导性非常严重,删了吧,
另外注册失败,邮箱迟迟不发送

**Comment by kexxxfeng** [comment]
您好，麻烦您查看一下是不是在垃圾箱里？

**Comment by cnblogs-team** [comment]
您好，麻烦您提供一下注册时填写的显示名称

**Comment by angieCat** [comment]
> 您好，麻烦您查看一下是不是在垃圾箱里？

是的,在垃圾箱里,这个博文能不能删了,误导人

**Comment by cnblogs-team** [comment]
您好，建议您在那篇博文的评论中向博主反馈
