### ISSUE TITLE
在班级中发布作业出现400错误

### ISSUE THREAD

**Issue by YuRenDaZ** [cnblogs/coder-service#12]
我再编辑好作业以后点击发布但是服务器返回了400错误，并且页面没有任何变动

**Comment by cnblogs-team** [comment]
您好，您刷新重试也不行吗？我这边测试是可以发布作业的。

**Comment by YuRenDaZ** [comment]
还是不行 我换了浏览器和电脑都不行，我怀疑是不是内容原因

**Comment by cnblogs-team** [comment]
您好，能问一下是什么内容吗？还有方便把您的班级名称提供给我们吗？

**Comment by YuRenDaZ** [comment]
[https://edu.cnblogs.com/campus/xnsy/SoftwareEngineeringClass2](url)这是班级的地址，内容怎么发给你？

**Comment by cnblogs-team** [comment]
您好，您可以添加附件发送至contact@cnblogs.com。还有就是您更换内容后能发布吗？

**Comment by YuRenDaZ** [comment]
不可以 我试过了不是内容原因

**Comment by YuRenDaZ** [comment]
另外一个助教也试了也不行

**Comment by cnblogs-team** [comment]
您好，麻烦您按昵称添加“fanfantest”为助教，方便开发人员定位问题，谢谢您的配合！

**Comment by YuRenDaZ** [comment]
邀请了

**Comment by cnblogs-team** [comment]
您好，感谢您的配合，我们处理完毕会告知您的，请您耐心等待！

**Comment by cnblogs-team** [comment]
您好，麻烦您现在测试一下是否可以发布作业，我这边测试是可以的。

**Comment by YuRenDaZ** [comment]
可以了，到底是什么问题呢？

**Comment by cnblogs-team** [comment]
你们班级的编辑器类型未通过后端验证（产生了预设之外的值），具体的细节还需要进一步排查。
感谢您的反馈！

**Comment by YuRenDaZ** [comment]
这个班级存在同样的问题，请解决一下[https://edu.cnblogs.com/campus/xnsy/SoftwareEngineeringClass1](url)。谢谢

**Comment by cnblogs-team** [comment]
您好，现在应该可以了。目前的解决方法只是权宜之计，我们一定会找到根本原因并且解决。
目前此种情况只在您的学校出现过，其他学校似乎还未出现。

**Comment by YuRenDaZ** [comment]
好像问题还是没有解决，这个班还是不能发布作业

**Comment by cnblogs-team** [comment]
麻烦您再把刚刚那个账户邀请进去。

**Comment by cnblogs-team** [comment]
您可以切换一下编辑器（在编辑器右侧有个编辑器切换按钮），再进行发布，这样应该就可以了。

**Comment by YuRenDaZ** [comment]
可以了，麻烦了

**Comment by cnblogs-team** [comment]
您客气了，很抱歉！这都是我们的问题，彻底解决后我们会在此issue告知您。

**Comment by cnblogs-team** [comment]
您好，这个问题已经找到了根源并解决了，感谢您的反馈!
