### ISSUE TITLE
登录以及注册问题

### ISSUE THREAD

**Issue by AugustSpencer** [cnblogs/coder-service#125]
您好，
我在注册的时候发现邮箱已被绑定，需要使用其他邮箱。然后我认为我可能是已经有相应的博客园的账户，因此我转为登录，不过我不知道密码，所以使用该邮箱修改了密码了。但是在输入用户名和密码之后，点击登录提示**该用户名不存在**。
请问如上问题要怎么解决呢？

**Comment by cnblogs-team** [comment]
您好，可能是您登陆用户名输入错误，麻烦您提供一下您的注册邮箱。

**Comment by AugustSpencer** [comment]
我登录也是用的邮箱登录的。不过我不记得我的用户名了。
邮箱： 942975976@qq.com

**Comment by cnblogs-team** [comment]
您好，麻烦您用账户关联邮箱发邮件至 contact@cnblogs.com

**Comment by AugustSpencer** [comment]
已发送邮件，请注意查收。

**Comment by AugustSpencer** [comment]
问题已经解决。谢谢。
