### ISSUE TITLE
网站分类的统计数量不准确，

### ISSUE THREAD

**Issue by devJIeJie** [cnblogs/coder-service#127]
如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图
![777777777726](https://user-images.githubusercontent.com/33599372/65240967-04a18080-db15-11e9-8030-b3bb172952c3.png)
所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示，如图所示1

**Comment by cnblogs-team** [comment]
您好，网站分类已经很少有人在使用了，这样统计的结果也是正常的。

**Comment by cnblogs-team** [comment]
您好，这个数字统计的是当天的博文数。
