### ISSUE TITLE
博问回答问题，如何添加代码？

### ISSUE THREAD

**Issue by liuyunbin** [cnblogs/coder-service#128]
我在博问的回答中添加了一段 Python，但缩进被吃了，请问如何添加代码？找了半天也没找到

**Comment by cnblogs-team** [comment]
您好，假如您使用的是TinyMce编辑器，您可以在输入选框的列表栏功能按钮从右边往左第二个按钮"插入代码（推荐）"功能插入代码。
假如您使用的是Markdown编辑器您可以输入
\`\`\`Python  
  (此处为python代码)   
  \`\`\`
进行添加。

**Comment by liuyunbin** [comment]
多谢，我还以为有专门的按钮来插入代码。

**Comment by cnblogs-team** [comment]
我们后期会添加有按钮的Markdown编辑器，希望可以给您带来更多良好体验！

**Comment by cli8910** [comment]
```
{
    a:{
        b:{}
    }
}
```

**Comment by zhangxiaoxiaoshuai** [comment]
var (
	coins = 50
	users = []string{
		"Matthew", "Sarah", "Augustus", "Heidi", "Emilie", "Peter", "Giana", "Adriano", "Aaron", "Elizabeth",
	}
	distribution = make(map[string]int, len(users))
)

func dispatchCoin() (left int) {
	//依次拿名字
	for _, name := range users {
		getCoin := 0
		for _, letter := range name {
			if letter == 'e' || letter == 'E' {
				getCoin++
				coins--
			} else if letter == 'i' || letter == 'I' {
				getCoin += 2
				coins -= 2
			} else if letter == 'o' || letter == 'O' {
				getCoin += 3
				coins -= 3
			} else if letter == 'u' || letter == 'U' {
				getCoin += 4
				coins -= 4
			}
		}
		distribution[name] = getCoin
	}
	left = coins
	return
}

func main() {
	left := dispatchCoin()
	fmt.Println("剩下：", left)
	for k, v := range distribution {
		fmt.Printf("%s:%d\n", k, v)
	}
}

**Comment by zhangxiaoxiaoshuai** [comment]
`var (
	coins = 50
	users = []string{
		"Matthew", "Sarah", "Augustus", "Heidi", "Emilie", "Peter", "Giana", "Adriano", "Aaron", "Elizabeth",
	}
	distribution = make(map[string]int, len(users))
)

func dispatchCoin() (left int) {
	//依次拿名字
	for _, name := range users {
		getCoin := 0
		for _, letter := range name {
			if letter == 'e' || letter == 'E' {
				getCoin++
				coins--
			} else if letter == 'i' || letter == 'I' {
				getCoin += 2
				coins -= 2
			} else if letter == 'o' || letter == 'O' {
				getCoin += 3
				coins -= 3
			} else if letter == 'u' || letter == 'U' {
				getCoin += 4
				coins -= 4
			}
		}
		distribution[name] = getCoin
	}
	left = coins
	return
}

func main() {
	left := dispatchCoin()
	fmt.Println("剩下：", left)
	for k, v := range distribution {
		fmt.Printf("%s:%d\n", k, v)
	}
}
`

**Comment by zhangxiaoxiaoshuai** [comment]
``var (
	coins = 50
	users = []string{
		"Matthew", "Sarah", "Augustus", "Heidi", "Emilie", "Peter", "Giana", "Adriano", "Aaron", "Elizabeth",
	}
	distribution = make(map[string]int, len(users))
)

func dispatchCoin() (left int) {
	//依次拿名字
	for _, name := range users {
		getCoin := 0
		for _, letter := range name {
			if letter == 'e' || letter == 'E' {
				getCoin++
				coins--
			} else if letter == 'i' || letter == 'I' {
				getCoin += 2
				coins -= 2
			} else if letter == 'o' || letter == 'O' {
				getCoin += 3
				coins -= 3
			} else if letter == 'u' || letter == 'U' {
				getCoin += 4
				coins -= 4
			}
		}
		distribution[name] = getCoin
	}
	left = coins
	return
}

func main() {
	left := dispatchCoin()
	fmt.Println("剩下：", left)
	for k, v := range distribution {
		fmt.Printf("%s:%d\n", k, v)
	}
}
``

**Comment by 1541734425** [comment]
'''python
def findThreshold(model_name, distance_metric):

	base_threshold = {'cosine': 0.40, 'euclidean': 0.55, 'euclidean_l2': 0.75}

	thresholds = {
		'VGG-Face': {'cosine': 0.40, 'euclidean': 0.55, 'euclidean_l2': 0.75},
		'OpenFace': {'cosine': 0.10, 'euclidean': 0.55, 'euclidean_l2': 0.55},
		'Facenet':  {'cosine': 0.40, 'euclidean': 10, 'euclidean_l2': 0.80},
		'DeepFace': {'cosine': 0.23, 'euclidean': 64, 'euclidean_l2': 0.64},
		'DeepID': 	{'cosine': 0.015, 'euclidean': 45, 'euclidean_l2': 0.17},
		'Dlib': 	{'cosine': 0.07, 'euclidean': 0.6, 'euclidean_l2': 0.6},
		'ArcFace':  {'cosine': 0.6871912959056619, 'euclidean': 4.1591468986978075, 'euclidean_l2': 1.1315718048269017}
		}

	threshold = thresholds.get(model_name, base_threshold).get(distance_metric, 0.4)

	return threshold
'''

**Comment by 1541734425** [comment]
`def findThreshold(model_name, distance_metric):

	base_threshold = {'cosine': 0.40, 'euclidean': 0.55, 'euclidean_l2': 0.75}

	thresholds = {
		'VGG-Face': {'cosine': 0.40, 'euclidean': 0.55, 'euclidean_l2': 0.75},
		'OpenFace': {'cosine': 0.10, 'euclidean': 0.55, 'euclidean_l2': 0.55},
		'Facenet':  {'cosine': 0.40, 'euclidean': 10, 'euclidean_l2': 0.80},
		'DeepFace': {'cosine': 0.23, 'euclidean': 64, 'euclidean_l2': 0.64},
		'DeepID': 	{'cosine': 0.015, 'euclidean': 45, 'euclidean_l2': 0.17},
		'Dlib': 	{'cosine': 0.07, 'euclidean': 0.6, 'euclidean_l2': 0.6},
		'ArcFace':  {'cosine': 0.6871912959056619, 'euclidean': 4.1591468986978075, 'euclidean_l2': 1.1315718048269017}
		}

	threshold = thresholds.get(model_name, base_threshold).get(distance_metric, 0.4)

	return threshold`
