### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by futiantian** [cnblogs/coder-service#140]
搜索框输入不了数字和英文，只能输入中文，但是输入完成还删除不了。。。。。。

**Comment by cnblogs-team** [comment]
您好，请问您在哪个页面遇到了这个问题？

**Comment by futiantian** [comment]
快捷键都不好使了呦！！



------------------ 原始邮件 ------------------
发件人: "cnblogs-team"<notifications@github.com>;
发送时间: 2019年10月10日(星期四) 下午3:49
收件人: "cnblogs/coder-service"<coder-service@noreply.github.com>;
抄送: "似水年华"<1457293969@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cnblogs/coder-service] 问题 (#140)




您好，请问您在哪个页面遇到了这个问题？

**Comment by cnblogs-team** [comment]
您好，请问您在哪个页面遇到了这些问题？

**Comment by futiantian** [comment]
就是输入不了数字英文啊！只能输入中文。然后删除不了输入的内容。ctrl+f5页面不刷新


------------------ 原始邮件 ------------------
发件人: "cnblogs-team"<notifications@github.com>;
发送时间: 2019年10月10日(星期四) 下午3:57
收件人: "cnblogs/coder-service"<coder-service@noreply.github.com>;
抄送: "似水年华"<1457293969@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cnblogs/coder-service] 问题 (#140)




您好，请问您在哪个页面遇到了这些问题？

**Comment by cnblogs-team** [comment]
您好，请问您是在使用 https://zzk.cnblogs.com 时遇到了这个问题吗？

**Comment by futiantian** [comment]
是这个：https://www.cnblogs.com/



------------------ 原始邮件 ------------------
发件人: "cnblogs-team"<notifications@github.com>;
发送时间: 2019年10月10日(星期四) 下午4:01
收件人: "cnblogs/coder-service"<coder-service@noreply.github.com>;
抄送: "似水年华"<1457293969@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cnblogs/coder-service] 问题 (#140)




您好，请问您是在使用 https://zzk.cnblogs.com 时遇到了这个问题吗？

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，我们会尽快修复该问题，给您带来的不便，敬请谅解。

**Comment by cnblogs-team** [comment]
您好，该问题已修复，抱歉，给您带来麻烦了。
