### ISSUE TITLE
我的号被封了两年了...也该解封了吧?

### ISSUE THREAD

**Issue by suizhikuo** [cnblogs/coder-service#164]
我的号被封了两年了...也该解封了吧? 
我的邮箱:  suizhikuo@126.com  登录名 suizhikuo

**Comment by cnblogs-team** [comment]
您好，您的账号状态是正常的...

**Comment by suizhikuo** [comment]
> 您好，您的账号状态是正常的...

没有评论权限

**Comment by suizhikuo** [comment]
![image](https://user-images.githubusercontent.com/2050414/68376384-7bf1a900-0183-11ea-81dd-d36b76bd7890.png)

**Comment by suizhikuo** [comment]
![image](https://user-images.githubusercontent.com/2050414/68376419-8dd34c00-0183-11ea-98ac-3cc685cb1d69.png)

**Comment by suizhikuo** [comment]
抱歉！评论提交失败！错误信息：抱歉！您的帐户目前无法发布评论

**Comment by cnblogs-team** [comment]
您好，现已恢复。

**Comment by suizhikuo** [comment]
> 您好，现已恢复。

好几年了...总于解决了...亲人们啊...谢谢...[泪奔]
