### ISSUE TITLE
发布时间超过一个月的文章不能从首页移出，修改文章无法保存

### ISSUE THREAD

**Issue by j20cc** [cnblogs/coder-service#168]
修改文章后一直这样提示，无法保存，这是什么原因

**Comment by cnblogs-team** [comment]
您好，您看下下方的发布选项，把“发布到博客园首页”勾选上就可以了，我们会争对这个问题做出改进，给您带来的不便，我们向您表示抱歉！

**Comment by j20cc** [comment]
![20191111154138](https://user-images.githubusercontent.com/29476413/68569733-d51a4f00-0499-11ea-9518-60583c923349.png)
这里是灰色的，点不动，我试过了

**Comment by j20cc** [comment]
我改了页面css取消了disable发布成功了。。。。
这算不算你们的一个bug

**Comment by cnblogs-team** [comment]
您好，这是我们的bug，我们已经着手修复了，非常抱歉给您带来麻烦了！
麻烦您先使用旧版后台 https://i1.cnblogs.com/
