### ISSUE TITLE
建议：登录后进入首页，不能马上新建博客

### ISSUE THREAD

**Issue by Maple512** [cnblogs/coder-service#170]
我登录后，想马上写随笔，但登录后进入首页，没找到入口，要找很久才能找到在哪里新建/编辑。（个人感觉不是很友好，希望能改进一下）非常感谢

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，我们已经收到，后期在迭代开发的时候会考虑您的建议！

**Comment by Maple512** [comment]
谢谢
