### ISSUE TITLE
上次注册了一个账号 莫名其妙就被封了

### ISSUE THREAD

**Issue by 1833183060** [cnblogs/coder-service#173]
怎么回事

**Comment by cnblogs-team** [comment]
您好，麻烦您提供一下您的注册邮箱

**Comment by 1833183060** [comment]
1833183060@qq.com

**Comment by cnblogs-team** [comment]
您好，博客园是纯净的技术交流社区，是不允许发布任何形式的推广信息的，给您带来的不便，我们表示抱歉。

**Comment by 1833183060** [comment]
我没发布推广信息啊。好像就发了个测试文章，都没有链接，也没什么内容。具体什么内容忘了。
就算 发了违规内容 ，账号也不至于直接 封掉啊。还没有任何提示
你们这个样子谁敢用啊，说封就封，多亏我是新博客，要是内容很多，那不是很麻烦

**Comment by cnblogs-team** [comment]
您好，麻烦您发邮件至 contact@cnblogs.com
