### ISSUE TITLE
网站bug 修改之前发布的随笔，新增图片出不来啊？

### ISSUE THREAD

**Issue by zrf518** [cnblogs/coder-service#177]
![360截图20191125145621379](https://user-images.githubusercontent.com/32395201/69518984-e4b68f00-0f93-11ea-9bb3-16daf8ab8e3a.jpg)

 
更换浏览器多次上传都没有效果哦，一直都没有处理啊！

**Comment by cnblogs-team** [comment]
您好，已收到您的反馈，正在处理，请您稍候！

**Comment by cnblogs-team** [comment]
您好，请问现在还有问题吗？如果还有问题，麻烦您提供一下博客地址

**Comment by zrf518** [comment]
一样的问题，Chrome，360多个浏览器都是一样的效果！


&nbsp;很明显，你们网站的缓存的问题？还是数据curd的问题？&nbsp;


博客地址：(你们可以自己去测试自己的账号，自己一个礼拜之前的博客随笔，修改一下，再来看看效果啊)
https://www.cnblogs.com/Fengge518/p/11892050.html


BestRegards!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cnblogs-team"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 晚上9:26
收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;;
抄送:&nbsp;"做自己"<434669648@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cnblogs/coder-service] 网站bug 修改之前发布的随笔，新增图片就是出不来，傻鬼啊？ (#177)




您好，请问现在还有问题吗？如果还有问题，麻烦您提供一下博客地址

**Comment by cnblogs-team** [comment]
您好，请问现在还有这个问题吗？

**Comment by zrf518** [comment]
![nonononono](https://user-images.githubusercontent.com/32395201/69745155-a5976200-117c-11ea-995e-6b2c54d77d14.png)
还是没有解决，建议让你们专业的程序员来处理， 不知道你们那边是怎么调式或者测试的，这个bug应该是普遍的现象！

**Comment by zrf518** [comment]
我这边是修改之前发布过的随笔，后来修改新增了图片(拖拉上传并可以看到图片之后再提交修改的)，你们这个bug 99%应该是缓存或者是更新操作的问题，这个应该是普遍的bug,不是我账号的问题

**Comment by cnblogs-team** [comment]
您好，这个问题已经修复了，麻烦您重新上传一次。

如果问题依旧，劳烦您继续反馈给我们，万分感谢

**Comment by zrf518** [comment]
![360截图20191128110057128](https://user-images.githubusercontent.com/32395201/69773809-de602700-11ce-11ea-9495-0ab08db18ee2.jpg)
![360截图20191128110133538](https://user-images.githubusercontent.com/32395201/69773823-e91abc00-11ce-11ea-9891-3eb22ce4a2af.jpg)
![360截图20191128110253401](https://user-images.githubusercontent.com/32395201/69773833-efa93380-11ce-11ea-9666-fe86b7fad43c.jpg)

无语了啊，啥情况,，建议你们专业靠谱NB的程序员来处理！！！Tks!

**Comment by cnblogs-team** [comment]
您好，请问现在还有这个问题吗？

**Comment by zrf518** [comment]
> 我这边是修改之前发布过的随笔，后来修改新增了图片(拖拉上传并可以看到图片之后再提交修改的)，你们这个bug 99%应该是缓存或者是更新操作的问题，这个应该是普遍的bug,不是我账号的问题

可以了
