### ISSUE TITLE
不能评论

### ISSUE THREAD

**Issue by suizhikuo** [cnblogs/coder-service#179]
![image](https://user-images.githubusercontent.com/2050414/69530492-1425c580-0fad-11ea-9775-40ff4ca88c44.png)

**Comment by suizhikuo** [comment]
![image](https://user-images.githubusercontent.com/2050414/69530523-20118780-0fad-11ea-91a3-e2c5ba97e8c8.png)

**Comment by cnblogsTim** [comment]
@suizhikuo 您好，抱歉，给您带来了不好的体验，麻烦您刷新后重试，现在已经恢复了。详情请见：[【故障公告】docker swarm 集群问题造成新版博客后台故障](https://www.cnblogs.com/cmt/p/11929312.html)。

**Comment by suizhikuo** [comment]
> @suizhikuo 您好，抱歉，给您带来了不好的体验，麻烦您刷新后重试，现在已经恢复了。详情请见：[【故障公告】docker swarm 集群问题造成新版博客后台故障](https://www.cnblogs.com/cmt/p/11929312.html)。

好的.
