### ISSUE TITLE
IE浏览器无法正常显示

### ISSUE THREAD

**Issue by zcstation** [cnblogs/coder-service#180]
IE浏览器打开博客园部分博客时默认使用IE7版本，导致页面无法正常显示，jQuery无法使用，希望可以在页面的**head**中添加以下代码修正此问题`<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">`，谢谢。
![image](https://user-images.githubusercontent.com/21253205/69616836-359cb500-1072-11ea-89e7-ba0447b85b4b.png)

**Comment by cnblogs-team** [comment]
您好，已经添加，感谢您的反馈！
