### ISSUE TITLE
刚刚提交了开通博客的申请，估计要多久能通过

### ISSUE THREAD

**Issue by dawaisme** [cnblogs/coder-service#182]
刚刚提交了开通博客的申请，估计要多久能通过？
目前一直处于 排队的状态，这让我感觉很遥遥无期啊。
我的登陆账号：dawa大娃bigbaby
邮箱：381144567@qq.com
可以帮忙查询一下吗？感谢。

**Comment by cnblogs-team** [comment]
您好，您的博客申请已通过

**Comment by dawaisme** [comment]
> 您好，您的博客申请已通过
谢谢工作人员~
