### ISSUE TITLE
交了好几申请开通博客啥时能通过啊!

### ISSUE THREAD

**Issue by fire-130630** [cnblogs/coder-service#185]
提交了好几次开通博客的申请，估计要还要啥时才能开通啊？过总
一直处于排队的状态，这让我感觉很遥遥无期啊。
我的登录账号是
及时行乐ii 邮箱是z13051611671@163.com
可以帮忙查询一下么?感谢

**Comment by cnblogs-team** [comment]
很抱歉给您带来了麻烦，还请您再提交一次申请，请认真填写理由。

**Comment by fire-130630** [comment]
> 很抱歉给您带来了麻烦，还请您再提交一次申请，请认真填写理由。

我又提交了 麻烦了

**Comment by cnblogs-team** [comment]
您好，抱歉，麻烦您再重新提交一次

**Comment by fire-130630** [comment]
> 您好，抱歉，麻烦您再重新提交一次

ok
