### ISSUE TITLE
我登录不上去了呢

### ISSUE THREAD

**Issue by w8w8w8** [cnblogs/coder-service#186]
https://www.cnblogs.com/Yita/

**Comment by cnblogs-team** [comment]
您好，请问有什么错误提示吗？

**Comment by cnblogs-team** [comment]
您好，麻烦您将遇到的问题详情发邮件至 contact@cnblogs.com

**Comment by w8w8w8** [comment]
@cnblogs-team 已经发邮件到邮箱了，使用找回密码功能，但是搞不清当时用的啥邮箱注册的了

**Comment by cnblogs-team** [comment]
您好，请问您遇到的问题解决了吗？

**Comment by w8w8w8** [comment]
@cnblogs-team 问题解决了，我发邮件告诉解决了的，这里我就关闭了哈
