### ISSUE TITLE
像这种职业喷子，博客园就没办法处理下吗？实在不行麻烦给个举报入口行吗？看着恶心

### ISSUE THREAD

**Issue by funthing** [cnblogs/coder-service#190]
只要有华为相关的新闻，这人就跟疯狗一样四处咬人，呵，华为水军都打到博客园了。也没有个举报接口。博客园就是个技术交流社区，出来这么一个搅屎棍真的是影响心情。

https://home.cnblogs.com/u/ddxkjddx/

![博客园1](https://user-images.githubusercontent.com/34561900/70012418-5e133a80-15af-11ea-99ae-587553f63ba9.png)
![博客园2](https://user-images.githubusercontent.com/34561900/70012419-5eabd100-15af-11ea-9c4c-e6ebd793884b.png)
![博客园3](https://user-images.githubusercontent.com/34561900/70012421-5f446780-15af-11ea-8bbd-8288b0ede4e4.png)
![博客园4](https://user-images.githubusercontent.com/34561900/70012423-5f446780-15af-11ea-8639-0f0f592d30ef.png)
![博客园5](https://user-images.githubusercontent.com/34561900/70012424-5fdcfe00-15af-11ea-9357-2855807929f6.png)
![博客园6](https://user-images.githubusercontent.com/34561900/70012426-5fdcfe00-15af-11ea-9f60-4a2c1212da12.png)
![博客园7](https://user-images.githubusercontent.com/34561900/70012427-60759480-15af-11ea-94d6-328e469b414a.png)
![博客园8](https://user-images.githubusercontent.com/34561900/70012430-610e2b00-15af-11ea-9a19-cd9a69191423.png)
![博客园9](https://user-images.githubusercontent.com/34561900/70012435-61a6c180-15af-11ea-9ae6-617128b44091.png)
![博客园10](https://user-images.githubusercontent.com/34561900/70012442-623f5800-15af-11ea-8b77-0a01467df89a.png)
![博客园11](https://user-images.githubusercontent.com/34561900/70012447-62d7ee80-15af-11ea-8187-9fae06cae544.png)
![博客园12](https://user-images.githubusercontent.com/34561900/70012449-63708500-15af-11ea-8d59-405de1f168c0.png)
![博客园13](https://user-images.githubusercontent.com/34561900/70012451-64091b80-15af-11ea-9272-90d39fbb6d18.png)
![博客园14](https://user-images.githubusercontent.com/34561900/70012452-64a1b200-15af-11ea-9d3e-ee997f44a4d7.png)

**Comment by cnblogs-team** [comment]
您好，非常抱歉给您带来了不好的体验，您的反馈我们已收到，目前正在处理中哦。

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，已进行处理。

**Comment by funthing** [comment]
> 您好，感谢您的反馈，已进行处理。

您好，请问处理结果是什么呢？我不奢求封禁账号，只要骂人的评论删除了就行，给被骂的人一个尊重。谢谢。

**Comment by cnblogs-team** [comment]
您好，我们已对该用户有攻击性的言论进行了删除处理呢。
