### ISSUE TITLE
[建议] 建议博客园在文章页面的代码段使用mono字体

### ISSUE THREAD

**Issue by thouen** [cnblogs/coder-service#194]
建议博客园在文章页面的代码段使用mono等宽字体，提升代码阅读体验

**Comment by cnblogs-team** [comment]
您好，`mono` 不是我们推荐使用的等宽字体，您可以自己通过自定义css修改字体

**Comment by thouen** [comment]
应该是我没有表达清楚，我的意思是阅读他人博客中的代码使用`monospace`字体。[汗]
我现在写了个脚本临时顶替，还是希望博客园采纳我的建议。因为`monospace`确实比更清晰、更方便阅读，谢谢！

**Comment by cnblogs-team** [comment]
已收到您的建议，我们会在后续版本中进行改进。
