### ISSUE TITLE
添加一个新网摘页面的改进建议

### ISSUE THREAD

**Issue by ngyg** [cnblogs/coder-service#198]
“网址：标题： 标签：” 这三个是添加一个新网摘的输入项。
    ___ 我可以用TABLE键来从上到下切换。
___但是有一个很不方便的地方：只要用TABLE切换到了“标签”这项，再按下TABLE键就无法挪动了。
    ___如果我刚刚填写了新网摘的“网址、标题、标签”后，必须把手从键盘挪动到鼠标上点击“收藏按钮“。
___我的建议或者要求：可以用TABLE键继续切换下去到“收藏按钮”上，再点击ENTER就可以完成收藏，手不需要离开键盘。

**Comment by cnblogs-team** [comment]
感谢您的反馈，我们会在后续版本中改进。

**Comment by cnblogs-team** [comment]
您好，让您久等了，现已改进。
