### ISSUE TITLE
邮箱不能收到激活邮件

### ISSUE THREAD

**Issue by RobertCheng1** [cnblogs/coder-service#2]

**Comment by RobertCheng1** [comment]
我的邮箱是： cpxzaitaiyuan@126.com

**Comment by kexxxfeng** [comment]
麻烦您检查一下是否在垃圾箱里

**Comment by cnblogs-team** [comment]
您好，您现在可以用同样的用户名重新注册。

**Comment by yujuangithub0805** [comment]
您我的邮箱是 yja1016361650@163.com

**Comment by liwei118** [comment]
您好，我的邮箱是ww114105@163.com，一直收不到激活邮件

**Comment by cnblogs-team** [comment]
您好，假如邮箱没有收到激活邮件，首先核实一下是否邮箱地址输入错误，倘若无误，再检查一下邮箱的垃圾箱是否拦截了激活邮件。

**Comment by HesitationPencil** [comment]
您好，我的邮箱是youyuqianbi@163.com，一直收不到激活邮件   垃圾邮箱也没有

**Comment by cnblogs-team** [comment]
@HesitationPencil 您这应该是注册时输错了邮箱地址，麻烦您重新注册。

**Comment by HesitationPencil** [comment]
我重新注册的话 原来的登录名和昵称 都重复了
这个怎么搞呀

在 2019-03-08 17:30:05，"cnblogs-team" <notifications@github.com> 写道：


@HesitationPencil 您这应该是注册时输错了邮箱地址，麻烦您重新注册。

**Comment by cnblogs-team** [comment]
@HesitationPencil 请联系官方邮箱 contact@cnblogs.com，提供登录名和呢称等信息，工作人员会帮助您解决的。

**Comment by 2540168279** [comment]
我邮箱是15971151570@163.com一直没收到激活邮件

**Comment by cnblogs-team** [comment]
@2540168279 麻烦您发邮件至  contact@cnblogs.com
