### ISSUE TITLE
为何我的博文被移出了首页

### ISSUE THREAD

**Issue by MikeCheers** [cnblogs/coder-service#219]
收到如下消息，博文就被移出了首页：

> 您好，您的博文“《C# GDI+ 破境之道》：第一境 GDI+基础 —— 第三节：画圆形”被移出首页，由此给您带来麻烦，请谅解！

> 首页是分享知识的地方，我们对发布在首页的博文的基本要求是：原创精品，排版整齐，有足够的篇幅，与程序员相关，能够让读者从中学到知识。

> 如果工作人员处理不当，请您谅解并发邮件至 contact@cnblogs.com 与我们联系。

谁能解释一下，这是为何？然后回复了短消息，也发了邮件，就没有下文了？

**Comment by cnblogs-team** [comment]
您好，已邮件回复了您。
