### ISSUE TITLE
随笔数量没有正确更新

### ISSUE THREAD

**Issue by aloneCR** [cnblogs/coder-service#228]
今天我删除了很多文章，但是随笔数量并没有相应的更新。请修复这个Bug
![错误详情](https://user-images.githubusercontent.com/30072589/76756635-0c3e9b00-67c1-11ea-981f-24a5ec48ad90.png)

**Comment by cnblogs-team** [comment]
您好，请问您的博客地址什么？

**Comment by aloneCR** [comment]
你好，现在已经可以正常显示了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cnblogs-team"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 晚上6:02
收件人: "cnblogs/coder-service"<coder-service@noreply.github.com&gt;; 
抄送: "1466543680"<1466543680@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cnblogs/coder-service] 随笔数量没有正确更新 (#228)





 
您好，请问您的博客地址什么？
