### ISSUE TITLE
博客园上传图片显示异常

### ISSUE THREAD

**Issue by chenyanbin188** [cnblogs/coder-service#233]
具体操作步骤，请看gif图，请查验！！！！

![333](https://user-images.githubusercontent.com/56284973/77251855-b5870480-6c8b-11ea-9d6d-f0f66fd56a5b.gif)

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，今天修复了这问题。

**Comment by chenyanbin188** [comment]
好的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cnblogs-team"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 下午5:06
收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;;
抄送:&nbsp;"543210188"<543210188@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cnblogs/coder-service] 博客园上传图片显示异常 (#233)





 
您好，抱歉，给您带来麻烦了，今天修复了这问题。
