### ISSUE TITLE
markdown编辑器使用异常

### ISSUE THREAD

**Issue by CNFeffery** [cnblogs/coder-service#234]
之前可以正常显示的格式现在不能正常渲染了，且段落开头使用全角输入两个空格进行首行缩进的方法现在没效果了

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，问题与我们昨天更换 markdown 引擎有关，我们正在排查。

**Comment by cnblogs-team** [comment]
您好，请问除了全角空格问题，是否还有其他问题？

**Comment by CNFeffery** [comment]
> 您好，请问除了全角空格问题，是否还有其他问题？

@cnblogs-team 还存在一些格式渲染失败，以前是正常的：
![image](https://user-images.githubusercontent.com/49147660/77396310-7d440b00-6dde-11ea-8262-7de9dd66c9b9.png)

**Comment by CNFeffery** [comment]
@cnblogs-team 譬如我这篇文章中很多地方都显示不正常https://www.cnblogs.com/feffery/p/12361421.html

**Comment by CNFeffery** [comment]
@cnblogs-team 我把原文每一部分都加了一行空行就正常了，之前不加也能正常渲染 😭

**Comment by cnblogs-team** [comment]
您好，我们今天发布了改进后的 markdown 引擎，全角空格的问题已解决，请问您遇到的 markdown 问题是否已解决？

**Comment by CNFeffery** [comment]
@cnblogs-team 已经解决啦 谢谢~
