### ISSUE TITLE
Markdown 的图片渲染不出来

### ISSUE THREAD

**Issue by fanliyan** [cnblogs/coder-service#235]
以base64保存的图片在markdown里渲染不出来，之前是可以的，例如这个https://www.cnblogs.com/flythinking/p/12446303.html

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，问题与我们更换 markdown 引擎有关，我们正在想办法解决兼容问题

**Comment by cnblogs-team** [comment]
您好，请问您具体是什么地方图片加载不出来，我们这边查看到都是可以正常显示的。
![www](https://user-images.githubusercontent.com/48276564/77634588-2e3bd880-6f8c-11ea-8cbf-79563ece34ab.jpg)

**Comment by fanliyan** [comment]
之前是显示不出来的，后来你们应该是有同事解决了
