### ISSUE TITLE
关于创作文章图片的问题

### ISSUE THREAD

**Issue by FoxDaxian** [cnblogs/coder-service#236]
比如我使用markdown写了一篇文章，图片是![](地址)格式，cnblog好像不会自动识别并上床到自己的图床，而是直接显示，这可能导致图片访问403等问题。
请问有什么好的处理方法吗？或者有什么快捷的方式可以上传到cnblog的图床

**Comment by cnblogs-team** [comment]
您好，自动提取图片并上传的功能已在开发计划中考虑，目前需要麻烦您手动复制/粘贴上传。

**Comment by FoxDaxian** [comment]
好的，期待尽快上线。: )
