### ISSUE TITLE
我没设置只允许注册用户访问，也没广告，博客却要登录才能查看

### ISSUE THREAD

**Issue by WangPin-wp** [cnblogs/coder-service#246]
我没设置只允许注册用户访问，也没广告，博客却要登录才能查看，帮帮我设置一下吧

**Comment by lwp0201** [comment]
您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。
感谢您对博客园的支持。

**Comment by cnblogs-team** [comment]
您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。
感谢您对博客园的支持。

**Comment by cnblogs-team** [comment]
> 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看，帮帮我设置一下吧

您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。
感谢您对博客园的支持。

**Comment by WangPin-wp** [comment]
登录账号：WP-WangPin 昵称：WP-WangPin






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"梁君牧"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 上午10:40
收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;;
抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246)





 
您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。
 感谢您对博客园的支持。

**Comment by WangPin-wp** [comment]
账号：WP-WangPin 昵称：WP-WangPin




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cnblogs-team"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 上午10:42
收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;;
抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246)





 
您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。
 感谢您对博客园的支持。

**Comment by cnblogs-team** [comment]
> 登录账号：WP-WangPin 昵称：WP-WangPin
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"梁君牧"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月21日(星期二) 上午10:40 收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;; 抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246) 您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。 感谢您对博客园的支持。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，您的账户和博客都是昨天刚开通的。为了避免广告推广造成的影响，我们默认设置新用户第一天发布的博文默认需要登录才能访问，等审核人员审核通过后，以后就无需登录查看。
对您造成的不便表示歉意，希望您理解，感谢您的博客园的支持。

> 登录账号：WP-WangPin 昵称：WP-WangPin
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"梁君牧"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月21日(星期二) 上午10:40 收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;; 抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246) 您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。 感谢您对博客园的支持。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 账号：WP-WangPin 昵称：WP-WangPin
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"cnblogs-team"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月21日(星期二) 上午10:42 收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;; 抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246) 您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。 感谢您对博客园的支持。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，您的账户和博客都是昨天刚开通的。为了避免广告推广造成的影响，我们默认设置新用户第一天发布的博文默认需要登录才能访问，等审核人员审核通过后，以后就无需登录查看。
对您造成的不便表示歉意，希望您理解，感谢您的博客园的支持。

**Comment by WangPin-wp** [comment]
好的，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cnblogs-team"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 上午10:53
收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;;
抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246)





  
登录账号：WP-WangPin 昵称：WP-WangPin
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"梁君牧"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月21日(星期二) 上午10:40 收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;; 抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246) 您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。 感谢您对博客园的支持。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您好，您的账户和博客都是昨天刚开通的。为了避免广告推广造成的影响，我们默认设置新用户第一天发布的博文默认需要登录才能访问，等审核人员审核通过后，以后就无需登录查看。
 对您造成的不便表示歉意，希望您理解，感谢您的博客园的支持。
  
登录账号：WP-WangPin 昵称：WP-WangPin
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"梁君牧"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月21日(星期二) 上午10:40 收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;; 抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246) 您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。 感谢您对博客园的支持。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
   
账号：WP-WangPin 昵称：WP-WangPin
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"cnblogs-team"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月21日(星期二) 上午10:42 收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;; 抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246) 您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。 感谢您对博客园的支持。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您好，您的账户和博客都是昨天刚开通的。为了避免广告推广造成的影响，我们默认设置新用户第一天发布的博文默认需要登录才能访问，等审核人员审核通过后，以后就无需登录查看。
 对您造成的不便表示歉意，希望您理解，感谢您的博客园的支持。

**Comment by WangPin-wp** [comment]
账号：WP-WangPin




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"梁君牧"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 上午10:40
收件人:&nbsp;"cnblogs/coder-service"<coder-service@noreply.github.com&gt;;
抄送:&nbsp;"王品"<1480408054@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cnblogs/coder-service] 我没设置只允许注册用户访问，也没广告，博客却要登录才能查看 (#246)





 
您好，请提供一下您的登陆账号或者昵称，我们帮您查询一下您的账户情况。
 感谢您对博客园的支持。
