### ISSUE TITLE
账户停用通知

### ISSUE THREAD

**Issue by ghd258** [cnblogs/coder-service#248]
您好！博客园是面向程序员的IT技术学习网站。由于您在这里发布广告信息，您的账户被停用。由此给您带来的麻烦，请谅解！
   我以及很久没有发布文章了，何况发布什么广告，请问系统哪里查出来发布广告了，随便就禁用账号了

**Comment by cnblogs-team** [comment]
您好，已在邮件中回复您

**Comment by ghd258** [comment]
非常感谢 我以及删除了 并修改了密码
