### ISSUE TITLE
网站ico在黑暗模式中几乎不可见

### ISSUE THREAD

**Issue by sun-chong** [cnblogs/coder-service#249]
自从博客园更新了ico之后，「黑暗模式」的浏览器应用愈发广泛。但是[博客园的黑色ico](https://www.cnblogs.com/favicon.ico)，在黑暗模式的浏览器标签栏中，与背景融为一体，几乎是不可见的。
建议仿照GitHub，在黑色的主体标志外围**增加浅色的背景**，使得ico无论在正常模式或是黑暗模式都能够清晰可见。

**Comment by cnblogs-team** [comment]
您好，非常感谢您的建议，我们会对icon图标作改进的呢。
