### ISSUE TITLE
博客装修css代码失效

### ISSUE THREAD

**Issue by GC21** [cnblogs/coder-service#250]
为什么之前用的代码装饰css 失效了， 换成谷歌浏览器也不行， 感觉像是官方那里改动造成的。1、原来设置的图片圆角是有效的![](https://img2020.cnblogs.com/blog/1213778/202004/1213778-20200425121624117-1292869398.png)

2、原来设置代码黑色主题是有效的，css没有使用外链，不像是我这的问题。
![](https://img2020.cnblogs.com/blog/1213778/202004/1213778-20200425121844754-759300560.png)

**Comment by GC21** [comment]
博客地址：https://home.cnblogs.com/u/CH520/

**Comment by cnblogs-team** [comment]
@CHCH520 

您好，这边希望您能提供一下失效的 css 代码，我们排查一下看看。

**Comment by GC21** [comment]
#mainContent {
    margin-left: 250px!important;
    margin-right: 0px;
}
#mainContent .forFlow {
    margin-left: 250px;
    margin-right: 0px;
    min-width: 500px;
}
#sideBar {
    float: left;
    position: fixed;
    top: 25px;
}
#header {
    height: 35px;
}
#blogTitle {
    height: 35px;
}
#header #blogTitle h1 {
    display: none;
}
#sideBar #sideBarMain .newsItem {
    margin-right:5px;
    margin-left:5px;
}
#contact_qq img {
    margin:0px;
    height: 52px;
    width: 52px;
    border-radius: 26px;
    opacity: 1.0;
    border:1px solid;
}
#contact_qq img:hover {
    opacity: 0.7;
}
#contact_email img {
    height: 52px;
    width: 52px;
    margin:0px;
    border-radius: 26px;
    opacity: 1.0;
    border:1px solid;
}
#contact_email img:hover {
    opacity: 0.7;
}
#contact_gitee img {
    height: 52px;
    margin:0px;
    border-radius: 26px;
    opacity: 1.0;
    border:1px solid;
}
#contact_gitee img:hover {
    opacity: 0.7;
}
#player {
    margin-right:0px;
    margin-left:0px;
    border-radius: 5px;
}
.aplayer {
    font-family: Arial,Helvetica,sans-serif;
    margin: 0px 0px 5px 0px;
    box-shadow: 0 2px 2px 0 rgba(0,0,0,.14), 0 3px 1px -2px rgba(0,0,0,.2), 0 1px 5px 0 rgba(0,0,0,.12);
    overflow: hidden;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    line-height: normal;
    background-color: rgba(0,0,0,.05)!important;
}
#profile_block {
    margin-right:0px;
    margin-left:5px;
    margin-top: 10px;
    font-size: 15px;
    line-height:20px;
    text-align:left;
    font-family:"微软雅黑", "宋体", "黑体", Arial;
    line-height: 1.8;
    font-weight: bold;
}
#profile_block a {
    text-decoration: none;
}
#profile_block a:hover {
    color: #AA7A53;
}
#blogCalendar {
    font-family:"微软雅黑", "宋体", "黑体", Arial;
    font-weight: bold;
}
#google_q,#q {
    height:22px;
    width:120px;
    border:solid 1px #ccc;
    box-shadow:inset 0 0 3px #ddd;
    border-radius:4px;
}
.btn_my_zzk {
    font-family:'Microsoft Yahei';
    border:none;
    height:26px;
    width:60px;
    padding:1px;
    font-size:14px;
    cursor:pointer;
    position:relative;
    vertical-align:middle;
    display:inline-block;
    background:#55895B;
    border-radius:4px;
    color:#fff;
}
.btn_my_zzk:hover {
    background:#6DA47D;
}
.blogStats {
    height:48px;
    color:#fff;
    float: right;
    font-size:14px;
    margin-top: 14px;
    margin-right: 2px;
    text-align: right;
}
#sidebar_toptags .catListTag li {
    margin:5px 5px 0 0;
    height:25px;
    line-height: 20px;
    overflow: hidden;
    text-overflow:ellipsis;
    white-space: nowrap;
    font-size: 13px;
    font-weight: bold;
}
#sidebar_toptags .catListTag li a {
    text-decoration: none;
}
#sidebar_toptags .catListTag li a:hover {
    color:#936A32;
    font-size: 14px;
}
#sidebar_topviewedposts #topview_posts_wrap li {
    margin:5px 5px 0 0;
    height:25px;
    line-height: 20px;
    overflow: hidden;
    text-overflow:ellipsis;
    white-space: nowrap;
    font-size: 13px;
    font-weight: bold;
}
#sidebar_topviewedposts #topview_posts_wrap li a {
    text-decoration: none;
}
#sidebar_topviewedposts #topview_posts_wrap li a:hover {
    color:#936A32;
    font-size: 14px;
}
#mainContent {
    float:right;
    margin-top:0px;
    margin-left:15px;
    padding-top:0px;
    padding-bottom:0px;
    padding-left:0px;
    padding-right:0px;
}
#navigator {
    font-size:16px;
    height:48px;
    background:#55895B;
    text-align:center;
    margin-top:20px;
    margin-bottom:20px;
    border-radius: 4px 4px 4px 4px;
}
#navList {
    height:48px;
}
#navList li {
    margin:0 5px 0 0;
    height:48px;
    display:inline-block;
    float:left;
}
#navList li a {
    padding:0 10px;
    line-height:48px;
    border:0;
    color:#fff;
    display:-moz-inline-box;
    display:inline-block;
    padding-left: 25px;
}
#navList li a:hover {
    text-decoration:none;
    color:#fff;
    font-weight: bold;
}
#navList li:hover {
    background:#000000;
    font-size:17px;
}
#navigator ul li #blog_nav_rss,#navigator ul li #blog_nav_rss_image {
    display: none;
}
#taglist_title {
    line-height:70px;
    font-weight: bold;
    font-size: 21px;
}
#MyTag1_dtTagList {
    margin: 0 auto;
    width: 95%;
    padding: 30px;
    margin-top: 0px;
    margin-bottom: 0px;
    box-shadow: 0 2px 6px rgba(100, 100, 100, 0.5);
}
#taglist a {
    margin-left: 30px;
    font-family: "楷体", "黑体" ,"宋体", "华文行楷", "黑体" ,Arial;
    text-decoration:none;
    color: rgba(0, 0, 0, 0.7);
    font-size: 20px;
    line-height: 20px;
    font-weight: bold;
    padding: 2px 0 2px 2px;
}
#taglist a:hover {
    color: #AA7A53;
}
.dayTitle {
    display:none;
}
.day {
    margin:0 30 0px 0;
}
.postTitle {
    font-size:17px;
    font-weight:bold;
    color:#009CB5;
    border-left: 3px solid #21759b;
    margin-bottom: 10px;
    float: right;
    width: 100%;
    clear: both;
}
.postTitle a {
    color:#009CB5;
}
.postTitle a:link, .postTitle a:visited, .postTitle a:active {
    color: #21759b;
    transition: all 0.4s linear 0s;
}
.postTitle a:hover {
    margin-left: 30px;
    color: #0f3647;
    text-decoration: none;
}
.day .postTitle a {
    padding-left: 10px;
}
.c_b_p_desc {
    line-height:24px;
    color:#888;
}
.c_b_p_desc a:hover {
    text-decoration:none;
    border-bottom-width:1px;
    border-bottom-style:dotted;
}
.PostListTitle {
    padding-left: 25px;
}
#myposts .PostList {
    font-size:14px;
    line-height:24px;
    margin:10px 100;
    padding:20px;
    background:#F2F2F2;
    box-shadow:0 0 5px #aaa;
    border-radius:4px;
}
#myposts .postTitl2 a {
    color:#6DA47D;
    text-decoration: none;
}
#myposts .postTitl2 a:hover {
    color: #FFFFFF;
    text-decoration: none;
}
#myposts .PostList:hover {
    background:#0f3647;
    text-decoration: none;
    color:#FFFFFF;
    font-size:14px;
    font-weight:bold;
    transition: all 0.1s linear 0.1s;
}
#topics a:visited {
    text-decoration: none;
}
#topics a:link {
    text-decoration: none;
}
#topics .postTitle {
    font-size:17px;
    padding-left: 10px;
    word-wrap:break-word;
}
#cnblogs_post_body {
    color: black;
    font: 0.875em/1.5em "微软雅黑" , "PTSans" , "Arial" ,sans-serif;
    font-size: 18px;
    word-wrap:break-word;
}
#cnblogs_post_body p {
    line-height: 35px;
    font-size: 18px;
    padding-left: 10px;
}
#cnblogs_post_body h1 {
    border-radius: 4px 4px 4px 4px;
    box-shadow: 0 0 0 1px #5F5A4B, 1px 1px 6px 1px rgba(10, 10, 0, 0.5);
    color: #FFFFFF;
    font-family: "微软雅黑" , "宋体" , "黑体" ,Arial;
    font-family: "华文行楷","微软雅黑", "宋体", "黑体", Arial;
    font-family: "黑体","微软雅黑", "宋体", "黑体", Arial;
    font-family: "方正准圆","微软雅黑", "宋体", "黑体", Arial;
    background: #2B6695;
    font-size: 20px;
    height: 32px;
    line-height: 25px;
    font-weight: bold;
    margin: 18px 0 !important;
    padding: 10px 0 5px 10px;
    text-shadow: 2px 2px 3px #222222;
    word-wrap:break-word;
}
#cnblogs_post_body h2 {
    font-family: "宋体" , "黑体" ,Arial,"微软雅黑" , ;
    color: rgb(0,0,0,0.9);
    font-size: 18px;
    line-height: 35px;
    margin: 0px 0 !important;
    padding: 0px 0px 0px 10px;
    font-weight: bold;
    word-wrap:break-word;
}
#cnblogs_post_body h3 {
    border-radius: 4px 4px 4px 4px;
    color: rgb(0,0,0,0.8);
    font-family: "微软雅黑" , "宋体" , "黑体" ,Arial;
    font-size: 16px;
    line-height:30px;
    margin: 0px 0 !important;
    padding: 0px 0px 0px 0px;
    font-weight: bold;
    word-wrap:break-word;
}
#cnblogs_post_body p img {
    margin: 8px 8px 8px 8px;
}
#cnblogs_post_body ul li img {
    margin: 8px 8px 8px 8px;
}
#cnblogs_post_body ul li {
    margin-top: 0px;
    margin-bottom: 0px;
    line-height: 35px;
}
#cnblogs_post_body ul li p {
    padding-left: 0px;
}
#cnblogs_post_body ul li h2 {
    padding-left: 0px;
    line-height: 35px;
}
#cnblogs_post_body ul li pre {
    margin-left: 5px;
}
#cnblogs_post_body ul + pre {
    margin-left: 35px;
}
#cnblogs_post_body ul li ul + pre {
    margin-left: 35px;
}














#MySignature {
    display: none;
    background-color: #FFFFFF;
    border-radius: 10px;
    box-shadow: 1px 1px 1px #FFFFFF;
    padding: 10px;
    line-height: 1.5;
    text-shadow: 1px 1px 1px #FFF;
    font-size: 16px;
    font-family: 'Microsoft Yahei';
}
#green_channel {
    background:#6DA47D;
    padding-left:20px;
    font-weight:normal;
    font-size:15px;
    width: 95%;
    border:none;
    color:#fff;
    padding:20px;
    border-radius:10px 10px 10px 10px;
    */
}
#author_profile {
    margin: 20px;
    height:66px;
}
#author_profile_info {
    margin-top: 0px;
    margin-left: 0px;
    margin-bottom: 0px;
    height:66px;
}
#author_profile_info img{
    margin-top: 0px;
    margin-left: 0px;
    margin-bottom: 0px;
    height:66px;
    padding: 0px;
    border-radius:33px 33px 33px 33px;
    */
}
#author_profile_detail {
    height:66px;
    margin-left: 10px;
}
#author_profile_detail a {
    line-height: 22px;
    font-size: 16px;
    font-weight: bold;
    font-family: "华文行楷",'Microsoft YaHei',"Times New Roman";
    text-decoration: none;
    color:#1E1E3C;
}
#author_profile_detail a:hover {
    font-size: 17px;
    text-decoration: none;
    color:#75715e;
}
#div_digg {
    height:66px;
    margin-top: 20px;
    margin-bottom: 20px;
}
#div_digg .diggit{
    height:66px;
    padding: 0px;
    margin-top: 0px;
    width: 66px;
}
.buryit {
    display:none;
}
.diggword {
    display:none;
}
#post_next_prev {
    margin-top: 5px;
    line-height: 22px;
    font-size: 16px;
    margin-bottom: 5px;
    font-family: 'Microsoft YaHei',"华文行楷","Times New Roman";
    color:#272822;
    font-weight: bold;
}
#post_next_prev a {
    color:#272822;
}
#post_next_prev a:hover {
    font-size: 17px;
    text-decoration: none;
    color:#A6A22E;
}
#topics .postDesc {
    font-size: 14px;
    font-weight: bold;
    margin-right: 10px;
    margin-top: 0px;
}
#topics .postDesc a {
    text-decoration: none;
}
#comment_form {
    margin-top: 20px;
}
#comment_nav {
    float: right;
    font-size: 15px;
    font-weight: bold;
}
#comment_nav a {
    text-decoration: none;
}
#comment_form_container>p {
    font-size: 15px;
    font-weight: bold;
}
#comment_form_container .commentbox_main {
    margin-top: 20px;
}
#tbCommentBody {
    font-family:'MIcrosoft Yahei';
    margin-top:10px;
    width:95%;
    background:white;
    color:#333;
    border:2px solid #fff;
    box-shadow:inset 0 0 8px #aaa;
    padding:10px;
    height:120px;
    font-size:14px;
    min-height:120px;
    border-radius:4px 4px 4px 4px;
}
#commentbox_opt {
    height:50px;
}
#btn_comment_submit {
    font-family:'Microsoft Yahei';
    border:none;
    height:48px;
    width:120px;
    font-size:18px;
    cursor:pointer;
    position:relative;
    vertical-align:middle;
    display:inline-block;
    background:#55895B;
    color:#fff;
    border-radius:4px 4px 4px 4px;
}
#btn_comment_submit:hover {
    background:#6DA47D;
}
#commentbox_opt>a {
    display:none;
}
#footer {
    font-size:14px;
    margin:20px;
    padding:5px;
    text-align:center;
    background:#55895B;
    color:#DDD;
    padding-top: 12px;
    border-radius:4px 4px 0px 0px;
    margin-left:270px;
}
#cnblogs_c2 {
    display:none;
}
::-webkit-scrollbar {
    width: 4px;
    height: 4px;
}
::-webkit-scrollbar-track {
    background: rgb(255, 255, 255);
    border-radius: 8px;
}
::-webkit-scrollbar-thumb {
    background: rgb(201, 201, 202);
    border-radius: 8px;
}
::-webkit-scrollbar-thumb:hover {
    background: rgb(162, 162, 163);
}
#navigatorDiv {
    padding: 10px;
    position: fixed;
    bottom: 70px;
    left: 7px;
    box-shadow: 0 0 10px #0B4BA9;
    min-width: 235px;
    max-width:237px;
    max-height:370px;
    min-height: 370px;
    font-weight:bold;
    cursor:pointer;
    background-color:#DDDDCC;
    overflow-y:auto;
    border-radius:5px;
    font-size: 13px;
    z-index:9999;
}
#navigatorDiv dt {
    line-height: 23px;
}
#navigatorDiv dt a {
    color: #000000;
    text-decoration: none;
}
#navigatorDiv dt a:hover {
    color:#AA7A53;
}
#navigatorTitleDiv img {
    position: fixed;
    bottom: 20px;
    left: 12px;
    z-index:9998;
    border-radius:10px;
    border:1px solid;
    opacity: 0.7;
}
#navigatorTitleDiv img:hover {
    opacity: 1.0;
}
#cnblogs_c1 img {
    border:1px solid;
    border-radius:128px;
}
#cnblogs_c1 img:hover {
    border:2px solid #FFD700;
}
#ad_t2 a, #under_post_news a, #under_post_kb a {
    text-decoration: none;
    font-size: 15px;
}
#ad_t2 a:hover, #under_post_news a:hover, #under_post_kb a:hover {
    font-size: 16px;
    text-decoration: none;
    color:#A6A22E;
}
table {
    width: 98%;
    max-width: 100em;
    border: 1px solid #dedede;
    border-collapse: collapse;
    empty-cells: show;
    border:none!important;
}
#cnblogs_post_body table th, #cnblogs_post_body table td {
    height: 35px;
    width: 100px;
    border:none!important;
    padding: 0 10px;
    text-align:center!important;
    vertical-align:middle!important;
}
table th {
    font-weight: bold;
    text-align: center !important;
    background: rgba(158,188,226,0.2);
}
table tbody tr:nth-child(2n) {
    background: rgba(158,188,226,0.12);
}
table tr:hover {
    background: #FAFAFA;
}
table th {
    white-space: nowrap;
}
table td:nth-child(1) {
    white-space: nowrap;
}


/*
使用了Monokai Sublime的黑色主题皮肤，但是还存在样式冲突，需要自己修改
这个样式只适合使用makedown编写的博客
Monokai Sublime style. Derived from Monokai by noformnocontent http://nn.mit-license.org/
*/

pre {
    /*控制代码不换行*/
    white-space: pre;
    word-wrap: normal;
}

.cnblogs-markdown .hljs {
    display: block;
    overflow: auto;
    padding: 1.3em 2em !important;
    font-size: 16px !important;
    background: #272822 !important;
    color: #FFF;
    max-height: 700px;
}

.hljs,
.hljs-tag,
.hljs-subst {
    color: #f8f8f2;
}

.hljs-strong,
.hljs-emphasis {
    color: #a8a8a2;
}

.hljs-bullet,
.hljs-quote,
.hljs-number,
.hljs-regexp,
.hljs-literal,
.hljs-link {
    color: #ae81ff;
}

.hljs-code,
.hljs-title,
.hljs-section,
.hljs-selector-class {
    color: #a6e22e;
}

.hljs-strong {
    font-weight: bold;
}

.hljs-emphasis {
    font-style: italic;
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-name,
.hljs-attr {
    color: #f92672;
}

.hljs-symbol,
.hljs-attribute {
    color: #66d9ef;
}

.hljs-params,
.hljs-class .hljs-title {
    color: #f8f8f2;
}

.hljs-string,
.hljs-type,
.hljs-built_in,
.hljs-builtin-name,
.hljs-selector-id,
.hljs-selector-attr,
.hljs-selector-pseudo,
.hljs-addition,
.hljs-variable,
.hljs-template-variable {
    color: #e6db74;
}

.hljs-comment,
.hljs-deletion,
.hljs-meta {
    color: #75715e;
}

/* 黑色主题makedown代码结束 */

**Comment by GC21** [comment]
圆角边框问题已解决，现在还剩黑色代码主题问题

**Comment by GC21** [comment]
/*
使用了Monokai Sublime的黑色主题皮肤，但是还存在样式冲突，需要自己修改
这个样式只适合使用makedown编写的博客
Monokai Sublime style. Derived from Monokai by noformnocontent http://nn.mit-license.org/
*/

pre {
/控制代码不换行/
white-space: pre;
word-wrap: normal;
}

.cnblogs-markdown .hljs {
display: block;
overflow: auto;
padding: 1.3em 2em !important;
font-size: 16px !important;
background: #272822 !important;
color: #FFF;
max-height: 700px;
}

.hljs,
.hljs-tag,
.hljs-subst {
color: #f8f8f2;
}

.hljs-strong,
.hljs-emphasis {
color: #a8a8a2;
}

.hljs-bullet,
.hljs-quote,
.hljs-number,
.hljs-regexp,
.hljs-literal,
.hljs-link {
color: #ae81ff;
}

.hljs-code,
.hljs-title,
.hljs-section,
.hljs-selector-class {
color: #a6e22e;
}

.hljs-strong {
font-weight: bold;
}

.hljs-emphasis {
font-style: italic;
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-name,
.hljs-attr {
color: #f92672;
}

.hljs-symbol,
.hljs-attribute {
color: #66d9ef;
}

.hljs-params,
.hljs-class .hljs-title {
color: #f8f8f2;
}

.hljs-string,
.hljs-type,
.hljs-built_in,
.hljs-builtin-name,
.hljs-selector-id,
.hljs-selector-attr,
.hljs-selector-pseudo,
.hljs-addition,
.hljs-variable,
.hljs-template-variable {
color: #e6db74;
}

.hljs-comment,
.hljs-deletion,
.hljs-meta {
color: #75715e;
}

/* 黑色主题makedown代码结束 */

**Comment by cnblogs-team** [comment]
您好，您的主题代码失效是您设置了不支持高亮的语言造成的，您的 css 选择器指定了 hljs 类，如果语言不支持高亮是不会有这个类的。

您可以在博文中尝试输入以下代码进行对比


    ```oc
    some code
    ```

    ```cpp
    some code
    ```

**Comment by GC21** [comment]
上面的OC不支持，之前是支持的；下面的C++支持，这是第三方造成的吗，因为在第三方那里我已经够勾选了OC语言。这个是主题设置网站：https://highlightjs.org/static/demo/
