### ISSUE TITLE
今天登录博客园提示重置密码

### ISSUE THREAD

**Issue by somnusnrlq** [cnblogs/coder-service#256]
您的账户存在安全风险，需要重置密码后才能登录

我一登陆就提示我这个，不修改还不能登录， 问题是我输入邮箱提示我的邮箱 用户不存在

这让我怎么登录！！

**Comment by cnblogs-team** [comment]
您好，麻烦您将登录用户名发邮件至 contact@cnblogs.com

**Comment by InSkyCat** [comment]
同问，麻烦帮忙解决一下。感谢！

**Comment by ikesnowy** [comment]
@InSkyCat 

您好，麻烦您将登录用户名发邮件至 contact@cnblogs.com

**Comment by cnblogs-team** [comment]
@InSkyCat 

您好，麻烦您将登录用户名发邮件至 contact@cnblogs.com

**Comment by InSkyCat** [comment]
@cnblogs-team 嗯嗯，已发

**Comment by billqian** [comment]
我也碰到这个问题了，邮件已发，能重现应该是bug了

**Comment by somnusnrlq** [comment]
我的问题是自己想不起邮箱来了，博客园已回复提示相关邮箱  根据邮箱重置密码即可，弱密码需要重置不是bug

**Comment by billqian** [comment]
@somnusnrlq 问题是我输入邮箱提示我的邮箱 用户不存在 => 我的问题是这个，我的邮箱正确，能够正确接收邮件。

**Comment by cnblogs-team** [comment]
@billqian 您好，已回复了您的邮件，您的账号关联邮箱与通知邮箱不是同一个。

**Comment by billqian** [comment]
> @billqian 您好，已回复了您的邮件，您的账号关联邮箱与通知邮箱不是同一个。

收到，非常感谢！ & 非常抱歉，我自己搞错了。
