### ISSUE TITLE
文章都不显示了，页面空白

### ISSUE THREAD

**Issue by xjr7670** [cnblogs/coder-service#258]
首页是空白的（侧边的菜单还有），然后页面变得很长了（通过滚动条可看出）。在后台管理页面可以看到文章，但是点击文章里面页面也是空白的
这是首页：
![image](https://user-images.githubusercontent.com/7731794/81053003-02026880-8ef7-11ea-904f-218e5b452b07.png)

这是从后台管理面点进去的文章页面
![www cnblogs com_wuzhiblog_p_12439116 html](https://user-images.githubusercontent.com/7731794/81053115-2cecbc80-8ef7-11ea-96ca-f508e3546fad.png)

**Comment by xjr7670** [comment]
但是查看源代码的时候，是能看到有内容的，什么问题😥

**Comment by cnblogs-team** [comment]
您好，请问您的博客地址是什么？

**Comment by xjr7670** [comment]
> 您好，请问您的博客地址是什么？

https://www.cnblogs.com/wuzhiblog/

这个

**Comment by cnblogs-team** [comment]
@xjr7670 

您好，您的自定义 css 中有如下内容，把博文内容给挤出去了：

```css
/* 侧边栏容器 */
#sideBar {
    margin-left: 78%;
}
```

建议删除之后再试试呢。

**Comment by xjr7670** [comment]
去掉后正常了。

但是之前是没问题的呀，而且我最近也没有更改过 CSS 了。怎么会突然这样的 @cnblogs-team

**Comment by cnblogs-team** [comment]
您好，最近我们优化过这款皮肤的样式。
