### ISSUE TITLE
主页显示问题

### ISSUE THREAD

**Issue by lizhipeng1992** [cnblogs/coder-service#260]
![Inked无标题_LI](https://user-images.githubusercontent.com/7744526/81461178-85b0a380-91dc-11ea-97db-794ef0c20d27.jpg)

**Comment by lizhipeng1992** [comment]
图片上传有问题

**Comment by cnblogs-team** [comment]
> 图片上传有问题

您好，请问您可以更详细地描述下您反馈的问题吗
