### ISSUE TITLE
你们是不是太闲了给自己找点事做？

### ISSUE THREAD

**Issue by MagicMaker** [cnblogs/coder-service#262]
我的账户登陆时显示让我重置密码后登陆，点击后，让我输入注册邮箱，但是我已经不记得邮箱了，或者当时注册时根本没用邮箱，用户名和密码我都是知道的，就是进不去了，帮我解决下

你们是不是太闲了给自己找点事做？

**Comment by cnblogs-team** [comment]
您好，这是因为最近有大量老用户因为密码泄露而被盗号用于发垃圾广告所采取的措施，麻烦您邮件联系 contact@cnblogs.com 并提供账号相关信息。
