### ISSUE TITLE
zzk搜索结果重复

### ISSUE THREAD

**Issue by zchrissirhcz** [cnblogs/coder-service#270]
你好，我在使用zzk查找自己博客中的内容，发现每一条搜索结果，都紧接着重复出现了一次。

**Comment by cnblogs-team** [comment]
您好，请问的博客地址是什么？

**Comment by zchrissirhcz** [comment]
刚刚又试了一下，现在的结果没有重复了。

博客地址是https://www.cnblogs.com/zjutzz 。

另外有一个问题，搜索结果似乎不是很准确，例如我搜索"工作中C语言"，想要找的是自己的一篇名为"工作中C语言相关问题总结"的博客，该博客没有出现在结果中的第一条。

似乎不是完全按照文章标题来优先匹配的？

**Comment by cnblogs-team** [comment]
您好，对于匹配准确性的问题，我会进行改进。
