### ISSUE TITLE
一行较长的文字后面的文字被截断不显示

### ISSUE THREAD

**Issue by lovepika** [cnblogs/coder-service#271]
编辑器：TinyMCE
主题：SimpleMemory
文字在编辑器是显示正常的，预览时候出现文字行长不换行。(有的发生换行了，部分没有自动换行，而是被截断了)
如下图：
![图片](https://user-images.githubusercontent.com/17944369/83101412-ded96c00-a0e4-11ea-9b7f-bd85b47773dc.png)

**Comment by lovepika** [comment]
应该是主题的原因，换个主题显示正常

**Comment by cnblogs-team** [comment]
您好，谢谢您的反馈，我们会排查一下这个问题。

**Comment by cnblogs-team** [comment]
您好，希望能提供一下问题博文的链接以及您使用的浏览器信息。

**Comment by lovepika** [comment]
您好，更换主题后可以正常显示。应该是SimpleMemory主题的问题
我的浏览器信息为：Google Chrome， 版本 83.0.4103.61（正式版本） （64 位）
OS为：macOS 10.14.6

**Comment by cnblogs-team** [comment]
您好，这边观察到您的博文内容中带有样式，将主题自带皮肤的样式给覆盖了（`white-space = pre` 阻止了换行，对于侧边栏在左侧的皮肤不会出现问题）。

如果直接从其他网站复制粘贴内容到 tinyMCE 且没有清除样式就会出现这种情况，这边建议您剪切出现问题的内容，使用快捷键 Ctrl+Shift+V 进行无格式粘贴，再重新应用一下样式。

**Comment by lovepika** [comment]
谢谢，辛苦了。
