### ISSUE TITLE
博客园如何编辑公式（如用latex）

### ISSUE THREAD

**Issue by maruitao** [cnblogs/coder-service#279]
根据网上教程，在个人设置里 开通了启用数学公式，但是在写随笔时，编辑公式后，保存文章查看，依然发现公式无法使用，求解答

**Comment by maruitao** [comment]
环境 win10 + chrome

**Comment by cnblogs-team** [comment]
您好，能否提供一下您的博文链接呢，我们这边看一下哦。

**Comment by maruitao** [comment]
你好， 问题搞明白了， 是因为已经开起了一篇随笔，在编写过程中开启了使用公式，所以那一篇随笔不能使用公式，但新建的随笔可以使用公式。

**Comment by cnblogs-team** [comment]
您好，开启数学公式支持后，之前的随笔也是可以正常显示公式的。
