### ISSUE TITLE
账号被盗

### ISSUE THREAD

**Issue by smallidea** [cnblogs/coder-service#280]
6月5日，我访问自己的博客园地址的时候，发现地址无法访问，账号也无法登录。查看了自己的关联邮箱，6.4 早上收到邮件说我的博客园账号被盗了，于此同时检查了自己的关联邮箱也确实有被盗的可能性，赶紧更换密码，并启用双重验证。
6月6日，收到邮件，里面说我发送的邮件到了对方垃圾邮件里面，看来账号关联邮箱确实是被盗用了，而且还被用于发送垃圾邮件的用途。

目前还在等待处理中，重要的是里面的数据要可以恢复。

**Comment by cnblogs-team** [comment]
您好，请问您的博客地址是什么？

**Comment by smallidea** [comment]
已经恢复了，非常感谢博客园的维护团队。同时谴责这种恶意的盗号行为，应该追究这种人的法律责任。

**Comment by smallidea** [comment]
smallidea.cnblogs.com
