### ISSUE TITLE
【重大BUG】博客园大量网页被神马搜索引擎转码无法正常阅读

### ISSUE THREAD

**Issue by lisng** [cnblogs/coder-service#29]
这个问题出现很久了，如图（传不了附件）

大量的（应该不是全部，但是量非常大）博客园网页，在神马搜索，也就是UC浏览器自带搜索中，都是被转码的，而且转码后格式排版错乱非常影响阅读，还会插入一些乱七八糟的代码，插入广告也末可知。

非常影响体验！

重现方式： 手机神马搜索，或者手机上UC浏览器，直接搜索 “ XXX 博客园” （比如：“ HTML 博客园”）

重要性：UC浏览器是市场份额最大的移动浏览器，请园方务必重视。

解决方法：在博客园的页头加一些声明，禁止转码（没测试，请你们测试一下）
https://www.music4x.com/post/889
如何禁止百度、神马、搜狗等搜索引擎转码
   总结起来，其实很简单，代码如下：
     <head>
     <meta http-equiv=”Cache-Control” content=”no-transform” />
      <meta http-equiv=”Cache-Control” content=”no-siteapp” />
      </head>
  一般来说添加了代码之后，5天左右网站访问的时候就不会转码了，有人要问为啥没有说其他搜索引擎，其实其他搜索引擎也是遵守这些协议的。

**Comment by lisng** [comment]
[https://zm10.sm-tc.cn/?src=l4uLj4zF0NCIiIjRnJGdk5CYjNGckJLQnoyIm9CejYuWnJOajNDIyczIyc7O0ZeLkpM%3D&uid=7b66f7c7142c9b85d3041f182bed734d&hid=113b51b79b34c87f5e256e6150701401&pos=5&cid=9&time=1557996643728&from=click&restype=1&pagetype=0020004002000402&bu=news_natural&query=html+%E5%8D%9A%E5%AE%A2%E5%9B%AD&mode=&v=1&force=true&wap=false&uc_param_str=dnntnwvepffrgibijbprsvdsdichei](url) 比如这个链接。转码的太多太多，随便找的一个例子。

**Comment by lisng** [comment]
提示:原网页已由神马搜索转码, 内容由www.cnblogs.com提供.

**Comment by cnblogs-team** [comment]
您好，非常感谢您的建议！现已添加。
```html
<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
```
