### ISSUE TITLE
cnblogs被黑了

### ISSUE THREAD

**Issue by mqingqing123** [cnblogs/coder-service#291]
手机浏览器打开很多页面。例如 https://www.cnblogs.com/Kassadin/p/13149434.html 会强出类似病毒的弹窗，好像被注入了病毒。

**Comment by cnblogs-team** [comment]
您好，我们这边排查看看，感谢您的反馈

**Comment by cnblogs-team** [comment]
@mqingqing123 

您好，希望能提供一下弹窗的截图，我们这边未能复现您的问题。

**Comment by mqingqing123** [comment]
我用的是UC手机浏览器，访问www.cnblogs.com ，有些页面（不是所有页面）进去后，会提示要求下载手机浏览器，点击确定后，就要求你安装。
![2222](https://user-images.githubusercontent.com/22250695/84846386-40a44a80-b081-11ea-9e17-558955fadbfe.png)
![1111](https://user-images.githubusercontent.com/22250695/84846388-4306a480-b081-11ea-9e3d-3589b0a26913.png)

**Comment by cnblogs-team** [comment]
@mqingqing123

您好，方便提供一下您的手机型号，系统信息以及广告页网址吗，我们使用 小米10 + MIUI11 + UC 浏览器访问 https://www.cnblogs.com/Kassadin/p/13149434.html 没能复现问题。

**Comment by cnblogs-team** [comment]
您好，我们现在去掉了页面中的一处第三方代码，麻烦您现在试试。

**Comment by mqingqing123** [comment]
问题现在没有了。
