### ISSUE TITLE
博客园写文章无法选择常用选项

### ISSUE THREAD

**Issue by pythonwby** [cnblogs/coder-service#295]
我的博客园激活博客后写文章选项栏里没有网上说的那么多选项。
![5V3UXZY(M$)YE$5O%7YY0XX](https://user-images.githubusercontent.com/67252367/85247500-847fc100-b480-11ea-9e08-98edc8b1e2ae.png)
网上的图片中在“网站分类”选项栏里有很多类型，而我的却没有，并且其他的选项栏也不齐全，这是怎么回事呀？

**Comment by cnblogs-team** [comment]
您好，请提供一下您的账号信息。

**Comment by pythonwby** [comment]
我的博客是：https://www.cnblogs.com/wuboyuan-python/

**Comment by cnblogs-team** [comment]
您好，由于您发布的是`文章`，因此没有那么多的选项内容呢；建议您新建随笔哦。

**Comment by pythonwby** [comment]
好的
