### ISSUE TITLE
招聘频道-博客园公司详情页面链接错误

### ISSUE THREAD

**Issue by netcore-jroger** [cnblogs/coder-service#299]
页面地址：https://job.cnblogs.com/enterprise/10102/

点击公司网址链接：实际打开地址是 `https//www.cnblogs.com`，`https` 后面少了 `:`  号。

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，在排查了。

**Comment by cnblogs-team** [comment]
您好，已修复，谢谢您帮助我们发现这个低级错误。
