### ISSUE TITLE
博客园没有app嘛？

### ISSUE THREAD

**Issue by Alex-xuelei** [cnblogs/coder-service#3]

**Comment by cnblogs-team** [comment]
* IOS：请您在`AppStore`中下载
* Android：
![35695-20180501213008316-722063512](https://user-images.githubusercontent.com/48276564/53926419-507f6180-40be-11e9-9bac-70ed726166d4.png)

您好，如果您只是简单的浏览博文以及阅读新闻，您也可以使用微信小程序，搜索"博客园"。
