### ISSUE TITLE
博客园markdown编辑器有问题么？？？？

### ISSUE THREAD

**Issue by RyanOvO** [cnblogs/coder-service#30]
==类中的抽象方法是可变的，延迟到子类中实现==
如上，在写随笔以及提问时，正常应该是会标亮的，且背景色为黄色，但是博客园的编辑器不支持。希望修正下。

**Comment by ZeekoZhu** [comment]
据我所知，markdown 没有这种语法，比如你目前正在的提问的 GitHub 就不支持，建议你手写 HTML 来实现这样的效果：

```html
<span style="background-color: #FFFF00">Marked text</span>
```

**Comment by crestin** [comment]
有实时预览的功能吗？

**Comment by RyanOvO** [comment]
> 据我所知，markdown 没有这种语法，比如你目前正在的提问的 GitHub 就不支持，建议你手写 HTML 来实现这样的效果：
> 
> ```
> <span style="background-color: #FFFF00">Marked text</span>
> ```

**Comment by RyanOvO** [comment]
> 据我所知，markdown 没有这种语法，比如你目前正在的提问的 GitHub 就不支持，建议你手写 HTML 来实现这样的效果：
> 
> ```
> <span style="background-color: #FFFF00">Marked text</span>
> ```



> 据我所知，markdown 没有这种语法，比如你目前正在的提问的 GitHub 就不支持，建议你手写 HTML 来实现这样的效果：
> 
> ```
> <span style="background-color: #FFFF00">Marked text</span>
> ```

好的，谢谢。

**Comment by RyanOvO** [comment]
> 据我所知，markdown 没有这种语法，比如你目前正在的提问的 GitHub 就不支持，建议你手写 HTML 来实现这样的效果：
> 
> ```
> <span style="background-color: #FFFF00">Marked text</span>
> ```

好的谢谢。

**Comment by RyanOvO** [comment]
> 有实时预览的功能吗？

并没有。
