### ISSUE TITLE
Authorization_Code授权返回错误invalid_grant

### ISSUE THREAD

**Issue by weipan789** [cnblogs/coder-service#317]
根据文档 2.1 获取授权码

![image](https://user-images.githubusercontent.com/5847964/88060155-677e0100-cb98-11ea-84fb-1d92c96957e4.png)

![image](https://user-images.githubusercontent.com/5847964/88060226-8aa8b080-cb98-11ea-8bb7-65503272892e.png)

已经能获取code，截取Url中的code换取token，请求参数如图

![image](https://user-images.githubusercontent.com/5847964/88060643-16bad800-cb99-11ea-821a-3a9ffdc6bc43.png)
报错
```
{
    "error": "invalid_grant"
}
```
实在不知道哪里出了问题

**Comment by cnblogs-team** [comment]
您好，麻烦您再试试，可能是 authorization code 过期了。

**Comment by weipan789** [comment]
依然不行，在`https://oauth.cnblogs.com/connect/token` 参数中code,我任意输入字符内容，报的错误是一样的，我怀疑第一步操作拿到的code不对呢，第一步操作是用post发送个请求，内容如下
```
    <form action="https://oauth.cnblogs.com/connect/authorize" method="post" class="form-example">
      <div class="form-example">
        <label >client_id: </label>
        <input type="text" name="client_id" value="my_client_id" required>
      </div>

      <div class="form-example">
        <label >scope: </label>
        <input type="text" name="scope" value="openid profile CnBlogsApi offline_access" required>
      </div>

      <div class="form-example">
        <label >response_type: </label>
        <input type="text" name="response_type" value="code id_token" required>
      </div>

      <div class="form-example">
        <label >redirect_uri: </label>
        <input type="text" name="redirect_uri" value="https://oauth.cnblogs.com/auth/callback" required>
      </div>

      <div class="form-example">
        <label >state: </label>
        <input type="text" name="state" value="cnblogs.com" required>
      </div>

      <div class="form-example">
        <label >nonce: </label>
        <input type="text" name="nonce" value="cnblogs.com" required>
      </div>

      <div class="form-example">
        <input type="submit" value="Subscribe!">
      </div>
    </form>
```
登录之后，就重定向到`redirect_uri`对应的界面，显示`code`。另外我注册了一个新的账号，尝试授权，结果还是一样的

**Comment by weipan789** [comment]
第二步骤`Token Authorization_Code授权`具体内容
```
POST /connect/token HTTP/1.1
Host: oauth.cnblogs.com
Content-Type: application/x-www-form-urlencoded
```
参数
```
client_id:my_client_id
client_secret:my_client_secret
grant_type:authorization_code
code:my_code_from_step_one
redirect_uri:https://oauth.cnblos.com/auth/callback
```

**Comment by cnblogs-team** [comment]
您好，您的 redirect_uri 写错了

![image](https://user-images.githubusercontent.com/48276564/88149557-d3ad4300-cc32-11ea-8788-4cfc511e42a1.png)

您的 client_id 格式似乎也不太对，第一段似乎没有复制进来，建议您再检查一下呢。

**Comment by weipan789** [comment]
client_id 由于截图的原因，应该也不算是敏感信息的，我去掉了一部分。`client_id `和 `client_secret` 我故意写错，报的就是其他错误了。第二步骤中的`redirect_uri `，不管写的对错，都是一样的错误。

不管怎样，还是非常感谢你帮我看这个问题。暂时先不用API的功能了。
