### ISSUE TITLE
麻烦加急处理。谢谢

### ISSUE THREAD

**Issue by BinFinn** [cnblogs/coder-service#32]
最近在园内多次寻求互联网技术及相关解决方案，虽然都有得到解决，但是另一个问题非常明显，园内所有帖子不仅是空白的地方只要鼠标发生点击都有可能触发弹窗、打开新的网页。一开始我怀疑是我自己电脑问题，但是我看其它网站不管进行什么操作都不会发生在博客园的情况。希望博客园加强净化园内浏览体验、解决这种恶意且不良的行为。谢谢、致敬博客园！

**Comment by xiaqs** [comment]
对了，我的生产环境如下：
Windows10 64位 1809（17763.503）
chrome版本 74.0.3729.131（正式版本）（64 位）

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，我们会加强管理的，如果您再遇到这样的情况，可以把链接地址反馈给我们，这样有助于定位问题。

**Comment by xiaqs** [comment]
在园内空白地方无规律点击，就会打开新标签页 地址是：about:blank

**Comment by xiaqs** [comment]
刚刚点击又打开这个网址了。http://xml.seavibes.club/redirect?feed=150055&auth=I3IPwh&subid=35002&query=&url=https%3A%2F%2Fwww.cnblogs.com%2FHighdoudou%2Fp%2F9993870.html&rnd=161

**Comment by cnblogs-team** [comment]
您是在这篇博文 https://www.cnblogs.com/Highdoudou/p/9993870.html 中点击的吗？

**Comment by xiaqs** [comment]
是的。

**Comment by xiaqs** [comment]
换了一个园内贴也有同样的问题。http://xml.seavibes.club/redirect?feed=150055&auth=I3IPwh&subid=35002&query=&url=https%3A%2F%2Fwww.cnblogs.com%2FppJuan%2Fp%2F7151000.html&rnd=230

**Comment by xiaqs** [comment]
如果是我本机浏览器的问题，麻烦也帮忙看下是什么问题。谢谢，因为在其它网站看帖子不会又这种情况。

**Comment by cnblogs-team** [comment]
您好，我这边测试都是没有这个问题的，建议您这使用其他终端打开这两个页面试试。

https://www.cnblogs.com/Highdoudou/p/9993870.html

http://www.cnblogs.com/ppJuan/p/7151000.html

**Comment by xiaqs** [comment]
我本地也是只有谷歌浏览器有这个问题。其它浏览器没有这个问题的。😭

**Comment by cnblogs-team** [comment]
您好，这个问题可能是您电脑上安装的某个软件引起的，之前遇到过广告拦截软件ADSafe自己弹广告，详见 https://www.cnblogs.com/twzy/p/5763163.html

**Comment by xiaqs** [comment]
嗯嗯。谢谢，我会认真查看并解决的。另外一点 有理由只攻击博客园吗？这个情况目前我只发现在博客园有，所以就抱着希望您们解决优化，同时也希望获得更好的浏览体验。

**Comment by xiaqs** [comment]
😂 就你刚刚发给我的地址，点击也有这次跳转到这里了。http://www.linkonclick.com/jump/next.php?r=1903955。难受，再找不出来问题就换系统了。

**Comment by cnblogs-team** [comment]
您好，这是藏在您电脑上的恶意软件针对您经常访问的网站进行广告植入。

**Comment by xiaqs** [comment]
好的。那我排查下。如果有进展会给您反馈的。谢谢

**Comment by xiaqs** [comment]
我已经找到原因了。但是不知道什么原因产生的。我发现部分网站会被一个叫【Ads by GeoSmartDNS】的广告攻击，它在我一些网站内显示或者隐式的嵌入下面的代码，当用户点击它的图片或者透明的遮罩层就会打开页面跳转，非常影响用户体验。但是发现我们用户并不能直接找到原因去删除，通过搜索发现有一款软件叫做【SpyHunter5】的可以全局检查并删除危害项目。但是这个软件需要等待72小时才能获取免费试用机会。如果博客园有兴趣解决这个问题，可以参考以下代码对这个广告进行屏蔽。
<div class="SCvrY4w6" style="opacity: 1; top: 10px;"><div class="V7Sj5O60ER"><img class="ksfx8u84887" src="https://guid-a.akamaihd.net/?r=https%3A%2F%2Ft.1p1eqpotato.com%2Ft%2F%3Fs%3D50%26ts%3D1559388502243%26a%3D5cef6426846011e9a8790242ac110002%26b%3D5cef6426846011e9a8790242ac110002-7058%26r%3Dhttps%253A%252F%252Fs.rszimg.com%252Fsimg%253Fk%253D%25252Fimg%25252F0f74c32b-6581-40f4-9fb1-8064075c9f23.png%2526b%253Dmedia.rsimg.50rtx.com%2526rw%253D2%2526rh%253D1%2526mxw%253D2048%26suid%3D"><div class="V8Lmf2Ww7c"><div class="GX1XLJ8k">×</div><div class="H7P78Xi0f">Renew Norton License Now</div><div class="GdjE33HVsS">Your Norton Subscription Has Expired</div><div class="x30mS3gWiR">Norton</div></div></div><div class="ElmlYH14K">Ads by GeoSmartDNS</div></div>
