### ISSUE TITLE
标签id重复

### ISSUE THREAD

**Issue by Vision-Zhang** [cnblogs/coder-service#324]
![{{6@7X(6ZJGV2V1{MRIL$KI](https://user-images.githubusercontent.com/49146231/89014602-52e3fa80-d348-11ea-8db5-90161adfe84f.png)

**Comment by Vision-Zhang** [comment]
[DOM] Found 2 elements with non-unique id #zzk_search_input: (More info: https://goo.gl/9p2vKq) <input id=​"zzk_search_input" placeholder=​"搜索" type=​"text" onkeydown=​"return zzk_go_enter(event)​;​" tabindex=​"3">​

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，我们会尽快修复的

**Comment by cnblogs-team** [comment]
您好，该问题已经修复。
