### ISSUE TITLE
几年前注册过，账户密码是正确的，提示重置密码但找不到入口？

### ISSUE THREAD

**Issue by lithbitren** [cnblogs/coder-service#330]

**Comment by cnblogs-team** [comment]
您好，您的邮箱是一个 gmail 邮箱，您可以在这个链接进行密码重置操作：https://account.cnblogs.com/resetpassword

**Comment by lithbitren** [comment]
> 您好，您的邮箱是一个 gmail 邮箱，您可以在这个链接进行密码重置操作：https://account.cnblogs.com/resetpassword

才想起来还有gmail，找回来了，蟹蟹
