### ISSUE TITLE
后台标签管理中，操作栏为空

### ISSUE THREAD

**Issue by Y80** [cnblogs/coder-service#334]
后台的标签管理地址应该是 https://i.cnblogs.com/tags 吧？
为什么在操作栏中什么也没有呢？
![image](https://user-images.githubusercontent.com/40132433/90104616-2a5ff580-dd77-11ea-90ae-39ae46c4fc6a.png)

**Comment by cnblogs-team** [comment]
您好，不同页卡的左侧边栏对应的操作都不一样的哦；标签页卡可进行的`编辑/删除`操作都已在每个对应的标签名称右侧列出呢。

**Comment by Y80** [comment]
> 您好，不同页卡的左侧边栏对应的操作都不一样的哦；标签页卡可进行的`编辑/删除`操作都已在每个对应的标签名称右侧列出呢。

所以我应该如何添加标签？

**Comment by Y80** [comment]
> > 您好，不同页卡的左侧边栏对应的操作都不一样的哦；标签页卡可进行的`编辑/删除`操作都已在每个对应的标签名称右侧列出呢。
> 
> 所以我应该如何添加标签？

我找到添加标签的方法了：在随笔/文章的编辑页面，选择标签时直接输入新的标签名，然后回车，发布后就自动生成了新的标签。

在标签管理 tab 中累死也找不到新建标签的功能。

交互感人 👍
