### ISSUE TITLE
请问换绑手机号的时候，输入新的手机号后，接收验证码的方式能否改成可选？

### ISSUE THREAD

**Issue by msglog** [cnblogs/coder-service#336]
请问换绑手机号的时候，输入新的手机号后，接收验证码的方式能否改成可选？

例如 若我已绑定的邮箱，则我可以选择使用邮箱来接收验证码。

电子邮箱地址基本很长一段时间都不会变更的，但是手机号这东西就不确定了。目前其他信息都正常的，想换绑一下手机号，结果非得要以前绑定的手机号接收验证码才能换绑手机！体验太不好了

**Comment by cnblogs-team** [comment]
您好，由于之前有一批用户的邮箱被盗进而导致博客园账户被盗，不得已在重置密码时加入了手机验证，很抱歉给您带来不便了，请发邮件至博客园官方邮箱 (contact@cnblogs.com) ，并提供一下您的账号信息

**Comment by msglog** [comment]
已发



---原始邮件---
发件人: "cnblogs-team"<notifications@github.com&gt;
发送时间: 2020年8月24日(周一) 下午5:23
收件人: "cnblogs/coder-service"<coder-service@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"安静的堵住耳朵"<outputlog@qq.com&gt;;
主题: Re: [cnblogs/coder-service] 请问换绑手机号的时候，输入新的手机号后，接收验证码的方式能否改成可选？ (#336)




 
您好，由于之前有一批用户的邮箱被盗进而导致博客园账户被盗，不得已在重置密码时加入了手机验证，很抱歉给您带来不便了，请发邮件至博客园官方邮箱 (contact@cnblogs.com) ，并提供一下您的账号信息
