### ISSUE TITLE
api client 被吊销了

### ISSUE THREAD

**Issue by jihuayu** [cnblogs/coder-service#339]
可能因为太久没用。今天准备使用 client Api 时发现 cleint id 似乎被吊销了，auth2 登录时显示 unauthorized_client，能不能重新帮我开通一下，谢谢。

Client id：78207812-c4c3-4c17-8121-f22d5f3db284
申请时的邮箱：8042833@qq.com

**Comment by cnblogs-team** [comment]
您好，您的 Client 是正常状态的呢，建议参考文档检查一下请求方式是否正确

**Comment by jihuayu** [comment]
https://oauth.cnblogs.com/connect/authorize 这个接口是不是被关闭了，我还是显示 unauthorized_client，
但是使用https://oauth.cnblogs.com/connect/token 可以登录。

**Comment by cnblogs-team** [comment]
@jihuayu 

您好，请您将请求的代码发送到 contact@cnblogs.com，我们这边看一下。
