### ISSUE TITLE
获取答案提交列表接口返回 500

### ISSUE THREAD

**Issue by jihuayu** [cnblogs/coder-service#340]
此接口返回500 https://api.cnblogs.com/api/edu/homework/answers/10974
其他接口调用正常
尝试过不同的 homeworkId 均不为 500
API 文档地址为：https://api.cnblogs.com/help#904614d4f9154e21a41157c50fc6b0c7

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，我们会进行排查的

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，已经修复了

**Comment by jihuayu** [comment]
现在返回结果是 403 Forbidden，但是其他 API (比如：https://api.cnblogs.com/api/edu/answer/uncommitted/2193/10974) 均可调用。
是这个接口需要相应的助教权限才能查看嘛？

**Comment by ikesnowy** [comment]
@jihuayu 

您好，这个接口需要登录才可以使用。

**Comment by cnblogs-team** [comment]
@jihuayu 

您好，这个接口需要登录才可以使用
