### ISSUE TITLE
代码款总是有X滚动和Y滚动

### ISSUE THREAD

**Issue by beautifulzzzz** [cnblogs/coder-service#388]
![image](https://user-images.githubusercontent.com/6163589/100325288-5f7d1480-3003-11eb-91f8-c8ae349d9e66.png)

我的代码段总是多一个X滚动和Y滚动，我看是
pre{
     overflow: xxxx;
}
导致的

**Comment by cnblogs-team** [comment]
您好，该问题预计会在晚上发布的更新中修复

**Comment by beautifulzzzz** [comment]
多谢，已经解决
