### ISSUE TITLE
博客园不能自己结贴

### ISSUE THREAD

**Issue by zhangchunyuzhcy** [cnblogs/coder-service#40]
我的问题是我自己解决的，为什么，结贴时一定要选一个人来结贴，还得给他园豆

**Comment by cnblogs-team** [comment]
> 
> 
> 我的问题是我自己解决的，为什么，结贴时一定要选一个人来结贴，还得给他园豆

您好，目前的规则是这样的，自己回答不能获得园豆。

**Comment by zhangchunyuzhcy** [comment]
我明白，我可以不要园豆啊，但是为什么会出现这个问题？
![image](https://user-images.githubusercontent.com/24404456/58869181-505c2580-86f0-11e9-8952-c23757b48c0a.png)

难道我一定要用别人的答案结贴吗？
