### ISSUE TITLE
发生异常Metaweblog not working for your blog

### ISSUE THREAD

**Issue by c10udlnk** [cnblogs/coder-service#406]
你好，我使用外部工具（dotnet-cnblog）上传图片时，返回了异常 `XMLRPC FAULT [500]: "! Metaweblog not working for your blog"` ，请问出现的原因是什么呢？

（实际上，我试了几个工具，都返回了这个异常，我认为应该不是工具的问题）

博客园后台已设置【允许 MetaWeblog 博客客户端访问】

**Comment by cnblogs-team** [comment]
您好，与您的账号有关，麻烦您发邮件至 contact@cnblogs.com

**Comment by c10udlnk** [comment]
好的，谢谢！！
