### ISSUE TITLE
#blockquote标签中的code 没有格式化#blockquote中的hljs格式化不生效 [BUG]

### ISSUE THREAD

**Issue by joisun** [cnblogs/coder-service#409]
示例文章地址：
https://www.cnblogs.com/jaycethanks/p/15085010.html

博客园的更新导致的问题， 之前没有。 

注释块内的代码块格式化失效

![image](https://user-images.githubusercontent.com/44388103/127738666-6ad553e2-cd90-4e7d-8826-9f2b9f73a25c.png)

**Comment by jaycethanks** [comment]
语法错误
