### ISSUE TITLE
博客首页-随笔列表的第一篇会展开全文

### ISSUE THREAD

**Issue by shinyYangYang** [cnblogs/coder-service#410]
博客的首页，进入后，发现本来应该展示博客的列表的界面，但是第一条博客却会展开。

期望的样子：

<img width="1224" alt="截屏2023-11-23 23 36 11" src="https://github.com/cnblogs/coder-service/assets/26118834/e1c57841-a034-494d-9cde-9830766dfb56">

**但是 实际的样子：**

<img width="903" alt="截屏2023-11-23 23 37 25" src="https://github.com/cnblogs/coder-service/assets/26118834/dd769358-1704-45c1-9939-8cc552d72f6b">

**能看到第一篇文章是默认会展开的。**

这是选项的配置情况：
<img width="703" alt="截屏2023-11-23 23 38 53" src="https://github.com/cnblogs/coder-service/assets/26118834/e6d116e8-93a8-47ab-8bb0-309988c64c73">

查看了下生成的js代码，发现是博客主动去调用了获取文章内容的接口导致的。

    <div class="c_b_p_desc" id="postlist_description_4487909">
    摘要：        
    我是通过cocoachina 的一篇文章 跟着学习的&#160;http://www.cocoachina.com/ios/20150228/11206.html 这里我简单描述下 主要还是给我自己记忆的 如果大家感兴趣可以去看看这篇文章 http://www.cocoachina.com/ios/20150    <a href="https://www.cnblogs.com/studyios/p/4487909.html" class="c_b_p_desc_readmore">阅读全文</a>
    </div>
        <script>getBlogPostBody(4487909);</script>
    </div>

**这个getBlogPostBody函数会去请求 postbody/fulltext 接口，然后把文章内容插入进去。**

不知道是我误配置了或者什么原因，不知道如何解决这个问题。

**Comment by cnblogs-team** [comment]
您好，勾选 `首页仅列出标题与摘要` 即可解决。

**Comment by shinyYangYang** [comment]
谢谢， 问题已经解决！

**Comment by shinyYangYang** [comment]
关闭 issue！
