### ISSUE TITLE
自己的随笔列表页面下面的分页那里是有问题的

### ISSUE THREAD

**Issue by Heliner** [cnblogs/coder-service#42]
https://www.cnblogs.com/Heliner/default.html?page=2，比如这个页面下的分页在点击后会发生鬼畜，一会变大一会变小。你也许会认为我说的是这个按钮会从小变大，但是我说的是他真的会鬼畜，你试下就知道了，他会在大小之间频繁的切换。因为MarkDown不能上传视频所以我就只能上传视频到B站，稍后我会把链接补充上来

**Comment by Heliner** [comment]
这是视频演示的链接
https://www.bilibili.com/video/av54518870/

**Comment by SilentCC** [comment]
您好，我们已经在新版博客中修复了这个问题，不久就会发布了。

**Comment by Heliner** [comment]
好的，那我就关闭这个ISSUE了

**Comment by cnblogs-team** [comment]
您好，线上版本已修复这个问题。抱歉，给您带来麻烦了。
