### ISSUE TITLE
注册时写了12位电话

### ISSUE THREAD

**Issue by Yan286315** [cnblogs/coder-service#44]
我没有其他邮箱可以注册，希望麻烦帮忙改一下184734399776这是输入错误的手机，邮箱18473439776@163.com，麻烦可以帮忙改成正确手机吗18473439776，我收不到验证码不能激活

**Comment by cnblogs-team** [comment]
您好，请联系我们的官方邮箱 contact@cnblogs.com 

另外，请不要在公开自己的登录名和密码。
