### ISSUE TITLE
is:issue is:open 你们是傻逼吗，重置了N次密码了，每次还要和上次不一样，老子都不知道设置的是啥密码了。

### ISSUE THREAD

**Issue by Meterwhite** [cnblogs/coder-service#45]

**Comment by Meterwhite** [comment]
你自己仔细看看你们的密码，有多弱智
注：至少8位，最多30位，密码中必须包含字母、数字、英文特殊字符，不支持中文与全角符号。

**Comment by cnblogs-team** [comment]
您好，由于盗号猖獗，我们只能维持这样的密码复杂度，望理解。

建议您在密码中使用易记的特殊字符。

**Comment by MuMingErLaiYa** [comment]
> 您好，由于盗号猖獗，我们只能维持这样的密码复杂度，望理解。
> 
> 建议您在密码中使用易记的特殊字符。

我的号被盗了  邮箱好像也被更改了 找不回怎么办

**Comment by cnblogs-team** [comment]
> > 您好，由于盗号猖獗，我们只能维持这样的密码复杂度，望理解。
> > 建议您在密码中使用易记的特殊字符。
> 
> 我的号被盗了 邮箱好像也被更改了 找不回怎么办

您好，您可以发邮件到博客园邮箱（contact@cnblogs.com）反馈。
