### ISSUE TITLE
你好，我的账号luanyu可能因为涉嫌广告，被封了

### ISSUE THREAD

**Issue by 853270563** [cnblogs/coder-service#56]
你好，我的账号luanyu可能因为涉嫌广告，被封了，麻烦给我恢复一下可以吗，我把非技术的博文删了，里面还有好多我转载的技术博客需要学习的

**Comment by cnblogs-team** [comment]
您好，您最近申请的帐号仍在发布盗版图书信息，我们无法为您恢复被封禁的帐号。
