### ISSUE TITLE
博客园有计划改版吗？

### ISSUE THREAD

**Issue by zwwhnly** [cnblogs/coder-service#6]
自己是博客园的忠实粉丝，使用很多年了，不过多年来感觉博客园的风格一直未变，博客模板的数量也没有更新，建议设计一下UI，增加一些流行的模板，使博客园更高大上一些，期待博客园的突变……

**Comment by cnblogs-team** [comment]
您好，感谢您的反馈，我们一直在对园子进行改进，可能UI方面的改进略少一些，以致于让您觉得没有变化了，今年我们会全面对产品进行改革，请您拭目以待！

**Comment by terwer** [comment]
可以试试我的UI改进
https://github.com/terwer/new-cnblogs-style

@cnblogs-team @zwwhnly
