### ISSUE TITLE
收藏文章时标题乱码

### ISSUE THREAD

**Issue by imiyu** [cnblogs/coder-service#61]
例如 https://www.cnblogs.com/aguncn/p/10904902.html
点收藏该文时 标题显示乱码

**Comment by whyNotBeAGiy** [comment]
<img width="533" alt="屏幕快照 2019-07-15 下午5 18 29" src="https://user-images.githubusercontent.com/28673566/61206329-df635100-a724-11e9-85d8-b6934839319e.png">
您好，经过c w测试 并未乱码，请您重试

**Comment by cnblogs-team** [comment]
您好。经过测试并未乱码，请您重试
<img width="533" alt="屏幕快照 2019-07-15 下午5 18 29" src="https://user-images.githubusercontent.com/48276564/61206405-0cafff00-a725-11e9-9bd9-431721d17d24.png">

**Comment by cnblogs-team** [comment]
您好，请问您用的是什么浏览器？

**Comment by imiyu** [comment]
搜狗浏览器，这是第二次出现了，不过刚才再试也不是乱码了。

**Comment by cnblogs-team** [comment]
谢谢您的反馈，我们会提交给技术人员

**Comment by cnblogs-team** [comment]
如果下次再出现类似情况，建议您直接发邮箱，这样能能快处理

**Comment by cnblogs-team** [comment]
如果下次再出现类似情况，建议您直接发邮箱，这样能能快处理
