### ISSUE TITLE
Two questions about the Metaweblog API documentation

### ISSUE THREAD

**Issue by JasonLiuLiuLiuLiu** [cnblogs/coder-service#63]
Dear Supporter,

I am bit confused when investigating the metaweblog api documentation, The url of the metaweblog is: [https://rpc.cnblogs.com/metaweblog/CoderAyu](https://rpc.cnblogs.com/metaweblog/CoderAyu) 

Q1: What kind of data type is `any` as shown below?
![image](https://user-images.githubusercontent.com/23184470/61580943-7461b200-ab4a-11e9-92ee-7dae7ad03044.png)
Q2: Some methods require appkey as parameter, what's `appkey` or how to get it?
![image](https://user-images.githubusercontent.com/23184470/61580971-d1f5fe80-ab4a-11e9-8657-6ddeedeaa63c.png)

Much Thanks! 
Your fans

**Comment by SilentCC** [comment]
@cnblogsTim  Could you take a look please?

**Comment by cnblogs-team** [comment]
The  following code is the Post definition in C#.
```cs
public struct Post
{
    public DateTime dateCreated;
    public string description;
    public string title;

    public string[] categories;
    public Enclosure enclosure;
    public string link;
    public string permalink;
    public object postid;
    public Source source;
    public string userid;

    public object mt_allow_comments;
    public object mt_allow_pings;
    public object mt_convert_breaks;
    public string mt_text_more;

    public string mt_excerpt;
    public string mt_keywords;

    public string wp_slug;
}

public struct Source
{
    public string name;
    public string url;
}
```
The apiKey should be ignored.

**Comment by JasonLiuLiuLiuLiu** [comment]
Ok, I understand, let me try.Thank you so much!
