### ISSUE TITLE
无法登录博客园，无语==

### ISSUE THREAD

**Issue by BuYishi** [cnblogs/coder-service#64]
![image](https://user-images.githubusercontent.com/20353688/61586901-c1786f00-abb0-11e9-8524-a2d99533a2a9.png)

**Comment by cnblogs-team** [comment]
您好，请问您使用的是什么浏览器、操作系统？

**Comment by BuYishi** [comment]
QQ浏览器和Edge都试过了，都不行
Win10




------------------ 原始邮件 ------------------
发件人: "cnblogs-team"<notifications@github.com>; 
发送时间: 2019年7月21日(星期天) 中午1:11
收件人: "cnblogs/coder-service"<coder-service@noreply.github.com>; 
抄送: "布衣食"<bu-ish@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cnblogs/coder-service] 无法登录博客园，无语== (#64)




您好，请问您使用的是什么浏览器、操作系统？

**Comment by cnblogs-team** [comment]
您好，我们这边测试了一下没能复现您的问题，麻烦您尝试一下在手机上能否登录。

**Comment by BuYishi** [comment]
真是无语了，我重新试了下，又能在电脑登录了==之前确实换了浏览器也登不了的==




------------------ 原始邮件 ------------------
发件人: "cnblogs-team"<notifications@github.com>; 
发送时间: 2019年7月21日(星期天) 中午1:35
收件人: "cnblogs/coder-service"<coder-service@noreply.github.com>; 
抄送: "布衣食"<bu-ish@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cnblogs/coder-service] 无法登录博客园，无语== (#64)




您好，我们这边测试了一下没能复现您的问题，麻烦您尝试一下在手机上能否登录。

**Comment by cnblogs-team** [comment]
您好，后续测试发现在某些情况下的确会出现这个问题，目前已经修复，感谢您的反馈。
