### ISSUE TITLE
我发表了一篇文章找不到了

### ISSUE THREAD

**Issue by Wscar** [cnblogs/coder-service#8]
账号 :wqawd520
文章标题可能叫 《使用nexus来搭建Nuget私服》。

**Comment by cnblogs-team** [comment]
您好，博客后台中也没有记录吗？

**Comment by Wscar** [comment]
随笔，日记，，文章，和草稿箱都没有。

**Comment by cnblogs-team** [comment]
是这篇 https://www.cnblogs.com/wscar/p/10474368.html 吗？

**Comment by Wscar** [comment]
是这篇，为什么我在我的文章，随笔，草稿箱中，都找不到这篇文章了， 如果是我误删除的，麻烦帮我恢复到随笔之中。反转麻烦帮我恢复到随笔之中，谢谢了

**Comment by cnblogs-team** [comment]
已为您恢复。
