### ISSUE TITLE
cnblogs.com/用户名 访问方式，随笔分类列表分类项自动添加(rss)后缀，如何取消

### ISSUE THREAD

**Issue by juejian** [cnblogs/coder-service#83]
<https://www.cnblogs.com/jsword> 访问方式，随笔分类列表分类项，自动添加(rss)后缀

![image](https://user-images.githubusercontent.com/12257223/63137880-9a278d00-c00a-11e9-9ffc-14b67d9dedf2.png)

但<https://jsword.cnblogs.com/>访问方式正常。

![image](https://user-images.githubusercontent.com/12257223/63137903-ba574c00-c00a-11e9-993c-c3c866058a7e.png)

**Comment by cnblogs-team** [comment]
您好，该问题修复。抱歉，给您带来麻烦了。
