### ISSUE TITLE
注册问题

### ISSUE THREAD

**Issue by incandescenth** [cnblogs/coder-service#9]
为什么注册的时候一直没有激活账号的邮件回复，邮箱激活不成功又不可登陆账号

**Comment by cnblogs-team** [comment]
您好，已回复了您的邮件

**Comment by kuntseng** [comment]
注册手机填错了，收不到信息，无法激活

**Comment by cnblogs-team** [comment]
@kuntseng 如果问题还没解决，麻烦您发邮件与我们联系

**Comment by dgfwork** [comment]
激活邮件失效了，重新注册号码和昵称又被占用了

**Comment by cnblogs-team** [comment]
@dgfwork 您好，请联系我们的官方邮箱 contact@cnblogs.com，会有工作人员帮您解决的。
