### ISSUE TITLE
【问题】自定义CSS失效了！

### ISSUE THREAD

**Issue by ahdung** [cnblogs/coder-service#97]
我使用的主题是`BlackSun`，自定义CSS失效，请检查处理。

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，我们会尽快修复这个问题。

**Comment by ahdung** [comment]
@cnblogs-team 谢谢。

题外，希望不要取消原有的反馈渠道：
[https://group.cnblogs.com/forum/help/newpost/](https://group.cnblogs.com/forum/help/newpost/)
[https://group.cnblogs.com/forum/ideas/newpost/](https://group.cnblogs.com/forum/ideas/newpost/)
[https://group.cnblogs.com/forum/bugs/newpost/](https://group.cnblogs.com/forum/bugs/newpost/)

因为你知道github对于国内来说并不是个稳定的地方，不是所有程序员都会翻墙，会翻墙的也不能保证梯子随时可用，所有在国内有个兜底的反馈渠道很重要。

**Comment by cnblogs-team** [comment]
@ahdung 您好，github和小组的反馈渠道都可以正常使用，您可以选择自己喜欢的渠道进行反馈。

**Comment by ahdung** [comment]
@cnblogs-team 说话有点逻辑性好不好，我说的是能不能访问的问题吗？

**Comment by cnblogs-team** [comment]
@ahdung 您好，原有的反馈渠道不会关闭，可以正常使用。
